from selenium.webdriver.common.by import By
import openpyxl
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
capa = DesiredCapabilities.CHROME
capa["pageLoadStrategy"] = "none"
from seleniumwire import webdriver


chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('window-size=1920x1480')






# options = webdriver.ChromeOptions()
# options.add_argument("--start-maximized")
# prefs = {"profile.default_content_settings.popups": 0,
#              "download.default_directory":
#                         r"C:\Users\truongtq.BA\PycharmProjects\pythonProject\ba_v2\excel",
#              "directory_upgrade": True}
# options.add_experimental_option("prefs", prefs)
# driver = webdriver.Chrome(options=options, desired_capabilities=capa)



def readData(file,sheetName,rownum,columnno):
    wordbook = openpyxl.load_workbook(file)
    sheet = wordbook.get_sheet_by_name(sheetName)
    return sheet.cell(row=rownum,column=columnno).value

def writeData(file,sheetName,rowum,columnno,data):
    wordbook = openpyxl.load_workbook(file)
    sheet = wordbook.get_sheet_by_name(sheetName)
    sheet.cell(row=rowum,column=columnno).value = data
    wordbook.save(file)


#đọc file config
f = open("file_config.txt", 'r')
for x in f:
     if x[0:11] == "- ModeTest:":   #1,2,3,4
         modetest = x[13:-2]
         # print(modetest)
     if x[0:11] == "- LinkTest:":   #https://gps.binhanh.vn
         linktest = x[13:-2]
     if x[0:10] == "- TimeRun:":    #09:41
         timerun = x[12:-2]
     if x[0:10] == "- LogPath:":    #C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/ba.log
         logpath = x[12:-2]
     if x[0:16] == "- CheckListPath:":  #C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/GPS_ChecklistForAutoTest_1.xlsx
         checklistpath = x[18:-2]
     if x[0:12] == "- ImagePath:":  #C:/Users/truongtq.BA/PycharmProjects/pythonProject/anhchup
         imagepath = x[14:-2]
     if x[0:15] == "- DataTestPath:":   #C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/data_ba.json
         datatestpath = x[17:-2]
     if x[0:13] == "- UploadPath:":     #C:/Users/truongtq.BA/PycharmProjects/pythonProject/file
         uploadpath = x[15:-2]
     if x[0:23] == "- LuuDuLieuTamThoiPath:":   #C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/bangluudulieu_tamthoi.xlsx
         path_luutamthoi = x[25:-2]
     if x[0:12] == "- ExcelPath:":      #C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/excel
         excelpath = x[14:-2]
     if x[0:13] == "- PathDriver:":     #C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/chromedriver.exe
         PATH = x[15:-2]
     if x[0:13] == "- ModuleTest:":     #0,1,2,3,4
         moduletest = x[15:-2]
     if x[0:20] == "- ExcelPathDownload:":      #C:\Users\truongtq.BA\PycharmProjects\pythonProject\ba_v2\excel
        excelpathdownload = x[22:-2]
        options = webdriver.ChromeOptions()
        options.add_argument("--start-maximized")
        prefs = {"profile.default_content_settings.popups": 0,
                     "download.default_directory":
                                r""+str(excelpathdownload),
                     "directory_upgrade": True}
        options.add_experimental_option("prefs", prefs)
        driver = webdriver.Chrome(options=options, desired_capabilities=capa)







login_user = "//*[@placeholder='Tên đăng nhập']"
login_password = "//*[@placeholder='Mật khẩu']"
login_ghinhodangnhap = "//*[@checked='checked']"
dangnhap = "//*[@id='UserLogin1_btnLogin']"

icon_bagps = "//*[@id='imgLogo']"
check_loginsai = "//*[text()='Tên đăng nhập hoặc mật khẩu không hợp lệ.']"
login_iconappstore = "//*[@src='/Images/Login/iconLogin/SVG/photo_logo-IOS.svg']"
check_login_appstore = "//*[text()='BA GPS']"

hopthoai = By.XPATH, "//*[@class='chat-list custom-scroll']//*[text()='Cảnh báo Autotest BA_GPS V2']"
hopthoai_input = By.XPATH, "//*[@id='editable-message-text']"
hopthoai_iconlink = By.XPATH, "//*[@class='icon icon-attach']"
hopthoai_iconlink_file = By.XPATH, "//*[@id='attach-menu-controls']/div/div[2]//*[@class='icon icon-document']"
hopthoai_send = By.XPATH, "//*[@class='modal-dialog']/div[2]//*[text()='Send']"
login_iconchplay = "//*[@src='/Images/Login/iconLogin/SVG/photo_logo-android.svg']"
login_icontrangchu = "//*[@src='../../Images/Login/iconLogin/SVG/ic_home.svg']"
login_iconlienhezalo = "//*[@id='lnkCallZalo']"
login_iconzalo_x = "//*[@src='../../Images/X.png']"
login_iconsodienthoai = "//*[@src='../../Images/Login/iconLogin/png-phone-icon-13.jpg']"
login_bagps = "//*[@id='lnkGlobal']"
login_hotlinemuahang = "//*[text()='HOTLINE MUA HÀNG']"
login_muasamsanpham = "//*[text()='MUA SẮM SẢN PHẨM']"
login_thongtingiaiphap = "//*[text()='THÔNG TIN GIẢI PHÁP']"
check_login_lienhezalo = "//*[@class='contactzalo-header']"
check_login_trangchu = "//*[@class='row align-items-center col-mar-5']/div[1]/a/img"
check_login_chplay = "//*[text()='BA GPS']"
check_login_muasamsanpham = "//*[text()='Sản phẩm ']"
login_vechungtoi = "//*[text()='VỀ CHÚNG TÔI']"
check_login_vechungtoi = "//*[@class='about-1 bg']/div/div[1]/div[1]/h1"
login_mangluoi = "//*[text()='MẠNG LƯỚI']"
check_login_mangluoi = "//*[@class='q-main-page']/div/h1"
login_huongdansudung = "//*[text()='HƯỚNG DẪN SỬ DỤNG']"
check_login_huongdansudung = "//*[@id='page-header']//*[text()='BA GPS']"
login_huongdandongphi = "//*[text()='HƯỚNG DẪN ĐÓNG PHÍ']"
check_login_huongdandongphi = "//*[@class='q-main-page v2 q-bg-gray']/div/div/div[1]/div/div[1]//*[text()='Hướng dẫn đóng phí dịch vụ BA GPS']"
linklienket_hopthoaizalo = "//*[@class='zalo-chat-widget']/iframe"
tiengviet = "/html/body/div/div[1]/div[1]/div/div/div[3]/div/div/div/div[1]"
english = "//*[@class='box-wrapper']//*[@class='zbtn zbtn-clear']"
chatnhanh = "//*[text()='Chat nhanh']"
hopthoaizalo_dau3cham = "//*[@class='far fa-ellipsis-h']"
hopthoaizalo_ketthuccuoctrochuyen = "//*[text()='Kết thúc cuộc trò chuyện']"
hopthoaizalo_icondong = "//*[@class='fal fa-chevron-down']"
check_login_iconzalo_doingonngu = "//*[@class='box__welcome']/h1"
check_login_iconzalo_chatnhanh = "//*[text()='Xin chào! BA GPS rất vui được hỗ trợ bạn.']"
iconngonngu_tienganh = "//*[@id='header-authentication']/div[3]/a//*[@src='/icons/flags/110-united%20kingdom.png']"
taikhoan = "//*[@id='header-authentication']//*[@id='lblAccount']"
dangxuat = "//*[text()='Đăng xuất']"
check_login_giamsat = "//*[@id='master-menu']//*[text()='Giám sát']"
check_login_khac = "//*[@id='master-menu']//*[text()='KHÁC']"
check_login_quantri = "//*[@id='master-menu']//*[text()='Quản trị']"


##GIÁM SÁT
menu_giamsat = "//*[@id='master-menu']//*[text()='Giám sát']"
timkiem_icon = "//*[@class='SearchSelect']"
timkiem_icon_timxe = "//*[@id='SelectSearchType']//*[@id='liVehicle']"
timkiem_icon_timdiachi = "//*[@id='SelectSearchType']//*[@id='liAddress']"
timkiem_icon_tendiem = "//*[@id='SelectSearchType']//*[@id='liLandmarkName']"
timkiem_icon_timtoado = "//*[@id='SelectSearchType']//*[@id='liLatLng']"
timkiem_timxe_input = "//*[@placeholder='Biển kiểm soát']"
timkiem_iconsearch = "//*[@id='SearchBtn']"
danhsachxe_tenphuongtien = "//*[@id='idClearOnline']/table/tbody/tr[1]/td[2]/div[2]"
saved = "//*[text()=' Saved ']"
timkiem_tendiem_input = "//*[@placeholder='Tên điểm']"
danhsachxe_tendiem = "//*[@class='ui-autocomplete ui-menu ui-widget ui-widget-content ui-corner-all']/li[1]/a"
timkiem_icon1 = "//*[@class='SearchSelect Landmark LandmarkName']"
timkiem_timtoado_input = "//*[@placeholder='Tọa độ']"
nhomxe = "//*[@id='ddlVehicleGroup']"
chonnhomxe1 = "//*[@id='ddlVehicleGroup']/option[2]"
bienso1 = "//*[@id='tblVehicleList']/tbody/tr[1]/td[2]/div[2]"
tatcanhomxe = "//*[@id='ddlVehicleGroup']//*[text()='Tất cả']"
trangthai = "//*[@id='ddlVehicleState']"
trangthai_batmay1 = "//*[@id='ddlVehicleState']//*[@value='1']"
checkiconxe_batmay1 = "//*[@id='tblVehicleList']/tbody/tr[2]/td[2]/div[1]/img"
soluong_dungbat = "//*[@id='tr_ColorSumVehicle']/td/table/tbody/tr[1]/td[2]/div"
soluong_dichuyen = "//*[@id='tr_ColorSumVehicle']/td/table/tbody/tr[1]/td[3]/div"
soluong_quatocdo = "//*[@id='tr_ColorSumVehicle']/td/table/tbody/tr[1]/td[4]/div"
tongsoxe_tren = "//*[@id='tr_ColorSumVehicle']/td/table/tbody/tr[1]/td[6]/div/div[1]"
trangthai_tatmay1 = "//*[@id='ddlVehicleState']//*[@value='2']"
soluong_dungtat = "//*[@id='tr_ColorSumVehicle']/td/table/tbody/tr[1]/td[1]/div"
trangthai_quatocdo = "//*[@id='ddlVehicleState']//*[@value='10']"
trangthai_dungdo = "//*[@id='ddlVehicleState']//*[@value='4']"
trangthai_dichuyen = "//*[@id='ddlVehicleState']//*[@value='3']"
trangthai_tatmay2 = "//*[@id='ddlVehicleState']//*[@value='8']"
trangthai_batmay2 = "//*[@id='ddlVehicleState']//*[@value='9']"
trangthai_mattinhieu = "//*[@id='ddlVehicleState']//*[@value='5']"
soluong_mattinhieu = "//*[@id='tr_ColorSumVehicle']/td/table/tbody/tr[1]/td[5]/div"
icon_xuatexcel = "//*[@class='tab-content']//*[@src='/Images/s_icon_excelExport.png']"
icon_capnhatdulieu = "//*[@class='tab-content']//*[@title='Cập nhật mới dữ liệu']"
icon_hientranghethong = "//*[@class='tab-content']//*[@title='Hiện trạng hệ thống']"
hientranghethong_x = "//*[@id='panelStatus']//*[@src='/Images/s_icon_x.png']"
icon_ynghiabieutuongxe = "//*[@src='/Images/s_icon_question.png']"
ynghiabieutuongxe_x = "//*[@id='closeMeaningOfIcon']"
xemlailotrinh = "//*[text()='Xem lại lộ trình ']"
tamgioganday = "//*[text()='8h gần đây']"
xemnhanh = "/html/body/div[17]/div[2]/div[2]/div[1]"
# xemnhanh = "//*[text()='Xem nhanh']"
check_popup_xemnhanhlotrinh = "//*[@id='divViewRouteQuick']"
xemnhanhlotrinh_xoa = "//*[@id='divViewRouteQuick']//*[@title='Xóa lộ trình']"
xemnhanhlotrinh_x = "//*[@id='divViewRouteQuick']//*[@title='Đóng']"
xemchitiettrencuasomoi = "/html/body/div[17]/div[2]/div[2]/div[2]"
# trongngay = "//*[text()='Trong ngày']"
trongngay = "/html/body/div[18]/div[2]/div[2]/div[9]"
tuychon = "/html/body/div[18]/div[2]/div[2]/div[10]"
nhapthongtinxe = "/html/body/div[20]/div[2]/div[2]/div[2]"
# nhapthongtinxe = "//*[text()='Nhập thông tin xe']"
popupthongtinxe_trongtaiinput = "//*[@id='vehicleInfomation']/div[2]/table/tbody/tr[6]/td[2]/input"
popupthongtinxe_capnhat = "//*[@id='ctl00_MainContent_vehicleInfoBGT_BtnUpdate']"
capnhatthanhcong = "//*[text()='Cập nhật thành công']"
ok = "//*[text()='OK']"
huy = "//*[@id='vehicleInfomation']//*[text()='Hủy']"
xemlotrinhnhieuxe = "/html/body/div[20]/div[2]/div[2]/div[3]"
hientrang = "/html/body/div[20]/div[2]/div[2]/div[4]"
check_danhsachxe_hientrang = "//*[@class='leaflet-popup-content-wrapper']"
gannhomdacbiet_hover = "//*[text()='Gán nhóm đặc biệt']"
themnhomdacbiet = "/html/body/div[19]/div[2]/div[2]/div"
check_themnhomdacbiet = "//*[@id='masterTwoColumnRight']/div/div/div/table/tbody/tr[1]/td"
anxe = "/html/body/div[20]/div[2]/div[2]/div[6]"
anxe_antoanbotrang = "//*[@id='panelHideVehicle']/div/div[2]/div[3]/div[2]/div/div[1]/input"
anxe_truyen = "//*[@id='panelHideVehicle']/div/div[2]/div[4]/div[2]/div/div[1]/input"
anxe_nguyennhan = "//*[@id='panelHideVehicle']/div/div[2]/div[5]/div[2]/select"
anxe_nguyennhan_xetainan = "//*[@id='panelHideVehicle']/div/div[2]/div[5]/div[2]/select//*[@value='3']"
anxe_ghichu = "//*[@id='panelHideVehicle']/div/div[2]/div[6]/div[2]/textarea"
luu = "//*[@id='panelHideVehicle']//*[text()='Lưu']"
icon_danhsachxedangan = "//*[@title='Danh sách xe đang ẩn']"
check_danhsachxedangan_tenphuongtien = "//*[@id='panelFavourite']/div/div[8]/table/tbody/tr[1]/td[2]"
icon_danhsachxedangan_x = "//*[@id='panelFavourite']/div/div[8]/table/tbody/tr[1]//*[@src='/Images/delete_item.png']"
thongtinthietbi = "/html/body/div[20]/div[2]/div[2]/div[7]"
check_danhsachxe_thongtinthietbi = "//*[@id='ui-dialog-title-divDeviceInfo']"
thongtinthietbi_x = "//*[@class='ui-icon ui-icon-closethick']"
xemhinhanhnhanh = "/html/body/div[20]/div[2]/div[2]/div[8]"
xemanhcamera = "/html/body/div[20]/div[2]/div[2]/div[9]"
check_xemanhcamera_tuchoitruycap = "//*[text()='Từ chối truy cập']"
xemanhcamera_nd10 = "/html/body/div[20]/div[2]/div[2]/div[10]"
check_xemanhcamera_nd10 = "//*[@id='cameraLeftPanel']/div/table/tbody/tr[1]/td"
giamsatcamera_nd10 = "/html/body/div[20]/div[2]/div[2]/div[11]"
check_giamsatcamera_nd10 = "//*[text()='Giám sát video']"
bieudonhienlieu = "/html/body/div[20]/div[2]/div[2]/div[12]"
check_popupbieudonhienlieu = "//*[@id='popUpBox']/div/div/div[2]"
bieudonhienlieu_x = "//*[@id='popUpBox']//*[@title='Đóng']"
bieudonhienlieumoi = "/html/body/div[20]/div[2]/div[2]/div[13]"
check_popupbieudonhienlieumoi = "//*[@class='popUpBox popup-online ui-draggable']/div/div/div[1]"
bieudonhienlieumoi_x = "//*[@class='popUpBox popup-online ui-draggable']//*[@title='Đóng']"
bieudonhietdo = "/html/body/div[20]/div[2]/div[2]/div[14]"
check_popupbieudonhietdo = "//*[text()='Xe chưa cấu hình hiển thị nhiệt độ.']"
khoangcachdencacxe = "/html/body/div[20]/div[2]/div[2]/div[15]"
khoancach_ngan = "//*[@class='float-left;']/table/tbody/tr[1]/td[1]"
khoancach_dai = "//*[@class='float-left;']/table/tbody/tr[1]/td[2]/div[3]"
button_keo = "//*[@class='float-left;']/table/tbody/tr[1]/td[2]/div[1]/div/a"
khoancachdencacxe_x = "//*[@id='panelMeasureDistance']/div/div[1]//*[@src='/Images/s_icon_x.png']"
khoangcachdencacdiem = "/html/body/div[20]/div[2]/div[2]/div[16]"
goicuoccamera = "//*[@pid='panelTabBacam1']"
popupthongtinxe_masorieng = "//*[@id='panelTabNormal1']/div[1]/div[1]"
popupthongtinxe_bienso = "//*[@id='panelTabNormal1']/div[1]/div[2]"
popupthongtinxe_giocapnhat = "//*[@id='panelTabNormal1']/div[1]/div[5]"
popupthongtinxe_vantocgps = "//*[@id='panelTabNormal1']/div[1]/div[8]"
popupthongtinxe_vantocco = "//*[@id='panelTabNormal1']/div[1]/div[11]"
popupthongtinxe_dungdo = "//*[@id='panelTabNormal1']/div[1]/div[14]"
popupthongtinxe_dangdo = "//*[@id='panelTabNormal1']/div[1]/div[16]"
popupthongtinxe_kmtrongngay = "//*[@id='panelTabNormal1']/div[1]/div[17]"
popupthongtinxe_may = "//*[@id='panelTabNormal1']/div[1]/div[20]"
popupthongtinxe_dieuhoa = "//*[@id='panelTabNormal1']/div[1]/div[23]"
popupthongtinxe_diachi = "//*[@id='panelTabNormal1']/div[1]/div[26]"
popupthongtinxe_nhienlieu = "//*[@id='panelTabNormal1']/div[1]/div[29]/div[2]"
popupthongtinxe_laixe = "//*[@id='panelTabNormal1']/div[2]/div[2]"
popupthongtinxe_dienthoai = "//*[@id='panelTabNormal1']/div[2]/div[4]"
popupthongtinxe_dienthoai1 = "//*[@id='panelTabNormal1']/div[2]/div[5]"
popupthongtinxe_giaypheplaixe = "//*[@id='panelTabNormal1']/div[2]/div[8]"
popupthongtinxe_quatocdo = "//*[@id='panelTabNormal1']/div[2]/div[11]"
popupthongtinxe_thoigianlaixelientuc = "//*[@id='panelTabNormal1']/div[2]/div[14]"
popupthongtinxe_thoigianlaixetrongngay = "//*[@id='panelTabNormal1']/div[2]/div[17]"
popupthongtinxe_thongtinthenho = "//*[@id='panelTabNormal1']/div[2]/div[20]"
popupthongtinxe_soquanly = "//*[@id='panelTabNormal1']/div[2]/div[23]"
popupthongtinxe_thongtinphi = "//*[@id='panelTabNormal1']/div[3]/div[2]"
popupthongtinxe_goicuocdichvuvienthong = "//*[@id='panelTabBacam1']/div[1]/div[5]"
popupthongtinxe_nhamang = "//*[@id='panelTabBacam1']/div[1]/div[8]"
popupthongtinxe_dungluonggoicuoc = "//*[@id='panelTabBacam1']/div[1]/div[11]"
popupthongtinxe_songayluutru = "//*[@id='panelTabBacam1']/div[1]/div[14]"
popupthongtinxe_sokenhluutru = "//*[@id='panelTabBacam1']/div[1]/div[17]"
popupthongtinxe_tinhnangdinhvi = "//*[@id='panelTabBacam1']/div[1]/div[20]"
popupthongtinxe_tinhnanganh = "//*[@id='panelTabBacam1']/div[1]/div[23]"
popupthongtinxe_tinhnangvideo = "//*[@id='panelTabBacam1']/div[1]/div[26]"
popupthongtinxe_kenhlapcamera = "//*[@id='panelTabBacam1']/div[1]/div[32]"
popupthongtinxe_kenhhoatdong = "//*[@id='panelTabBacam1']/div[1]/div[35]"
popupthongtinxe_dungluongocung = "//*[@id='panelTabBacam1']/div[1]/div[38]"
popupthongtinxe_mangketnoi = "//*[@id='panelTabBacam1']/div[1]/div[41]"
icon_hientranghethong1 = "//*[@class='toolboxRightButton']//*[@src='/Images/btn_rightPanel_hienTrang.png']"
hientranghethong_biensoinput = "//*[@id='panelStatus']/div/div[4]/table/tbody/tr/td[4]/input"
timkiem_icon2 = "//*[@class='SearchSelect']/span"
danhsachxe2g_x = "//*[@id='divListVehicle2G']//*[@src='/Images/s_icon_x.png']"
chuotphaimap_phongto = "/html/body/div[21]/div[2]/div[2]/div[1]"
chuotphaimap_thunho = "/html/body/div[21]/div[2]/div[2]/div[2]"
canhbaoquatocdo_x = "//*[@id='warningSpeedOverTimeLine']//*[@src='/icons/IconX.png']"
chuotphaimap_trungtamoday = "/html/body/div[21]/div[2]/div[2]/div[3]"
giamsat_iconphongto = "//*[@title='Zoom in']"
giamsat_iconthunho = "//*[@title='Zoom out']"
check_trungtamoday = "//*[text()='Bộ công an test']"
chuotphaimap_xemdiachi = "/html/body/div[21]/div[2]/div[2]/div[4]"
check_xemdiachi = "//*[@class='bootbox-body']"
chuotphaimap_dokhoangcach = "/html/body/div[21]/div[2]/div[2]/div[5]"
check_dokhoangcach_thongbao = "//*[@id='tdDistance']"
chuotphaimap_chihuong = "/html/body/div[21]/div[2]/div[2]/div[6]"
canhbao_x = "//*[@id='panelWarningOnline']//*[@src='/Images/s_icon_x.png']"
chihuong_diema = "//*[@src='/icons/DanDuong/diemdi.png']"
chihuong_diemb = "//*[@src='/icons/DanDuong/diemden.png']"
chihuong_googlemap = "//*[@id='btnGoGoogle']"
chihuong_chihuong = "//*[@id='btnGo']"
chihuong_icondaovitri = "//*[@src='/icons/DanDuong/refresh.png']"
chihuong_thoat = "//*[@id='btnExit']"
chuotphaimap_chidanduong = "/html/body/div[21]/div[2]/div[2]/div[7]"
chidanduong_diemdi = "//*[@id='ds_ds_new']/div[3]/table/tbody/tr[2]/td/div"
# chidanduong_diemden = "//*[@id='ds_ds_new']/div[3]/table/tbody/tr[4]/td/div"
chidanduong_diemden = "//*[@id='findroad_txtEnd']"
chidanduong_timchiduong = "//*[@id='findroad_btnSearch']"
chidanduong_loaixe = "//*[@id='findroad_bot_vehicletype']"
chidanduong_chiphicauduong = "//*[@id='findroad_detailscharge']/td"
chidanduong_chiphinhienlieu = "//*[@id='findroad_detailsfuel_hideshow']"
chidanduong_cacchiphikhac = "//*[@id='findroad_detailsother_hideshow']"
chidanduong_cacchiphikhac_chonloaiphi = "//*[@id='findroad_others_input']/td[2]/div/button"
chidanduong_diemdi_iconchon = "//*[@class='StartSearchBox SearchBox']/a/span"
chidanduong_diemdi_timxe = "//*[@id='StartliVehicle']"
chidanduong_diemdiinput = "//*[@id='findroad_txtStart']"
chidanduong_diemden_iconchon = "//*[@class='EndSearchSelect SearchSelect Address LatLng']/span"
chidanduong_diemden_timxe = "//*[@id='EndliVehicle']"
chidanduong_diemdeninput = "//*[@id='findroad_txtEnd']"
check_chidanduong_quangduong = "//*[@id='findroad_totaldistance']"
check_chidanduong_timtheodiem = "//*[@id='findroad_totalcost']"
check_chidanduong_giatien = "//*[@id='findroad_totalcost']"
chidanduong_diemdi_tendiem = "//*[@id='StartliLandmarkName']"
xe1 = "//*[@id='tblVehicleList']/tbody/tr[1]/td[2]"
xe2 = "//*[@id='tblVehicleList']/tbody/tr[2]/td[2]"
chidanduong_diemdi_tendiem1 = "//*[@id='StartliLandmarkName']"
chidanduong_diemdi_tendiem1input = "//*[@id='findroad_txtStart']"
chidanduong_diemden_tendiem1 = "//*[@id='StartliLandmarkName']"
chidanduong_diemden_tendiem1input = "//*[@id='findroad_txtEnd']"
chidanduong_diemden_iconchon2 = "//*[@class='EndSearchSelect SearchSelect LatLng']/span"
chidanduong_diemden_tendiem2 = "//*[@id='EndliLandmarkName']"
check_chidanduong_nhienlieu = "//*[@id='ds_ds_new']/div[3]/table/tbody/tr[12]/td/div[1]/table/tbody/tr[3]/td[3]"
timtheolotrinh = "//*[text()='Tìm theo lộ trình']"
chidanduong_nhomphuongtien = "//*[@id='findroad_ddlVehicleGroup']"
chidanduong_nhomphuongtien1 = "//*[@id='findroad_ddlVehicleGroup']/option[2]"
chidanduong_phuongtieninput = "//*[@placeholder='Chọn phương tiện']"
timtheolotrinh_giobatdau = "//*[@id='findroad_fromTimePicker']"
timtheolotrinh_gioketthuc = "//*[@id='findroad_toDatePicker']"
chuotphaimap_taodiembando = "/html/body/div[21]/div[2]/div[2]/div[9]"
taodiem_tendiem = "//*[@id='txtName']"
taodiem_laydiachibando = "//*[@id='chkAddressMap']"
taodiem_nhaptoado = "//*[@id='chkInputCoords']"
taodiem_kinhdo = "//*[@id='txtLongitude']"
taodiem_vido = "//*[@id='txtLatitude']"
taodiem_loaidiem = "//*[@id='ddlLandmarkType']"
taodiem_tenrieng = "//*[@id='txtPrivatename']"
taodiem_mota = "//*[@class='quantri-box popUpBox']//*[@id='txtDescription']"
taodiem_sophutdungdo = "//*[@id='txtNumberMinuteStop']"
taodiem_diemkiemsoat = "//*[@id='chkLandmarkManagement']"
taodiem_hienthidiem = "//*[@id='chkLandmarkVisible']"
taodiem_bankinh = "//*[@id='txtRadius']"
taodiem_huy = "//*[@id='btCancel']"
taodiem_luu = "//*[@id='btnSaveLandmark']"
check_message_taodiem = "//*[@class='bootbox modal fade bootbox-alert in']/div/div/div[1]"
check_message_taodiem1 = "//*[text()='Cập nhật thành công']"
taodiem_chon = "//*[@src='https://gps.binhanh.vn/icons/point/baido.png']"
taodiem_capnhat= "//*[@id='btnUpdateLandmark']"
taodiem_xoa = "//*[@id='btnDelete']"
check_message_xoadiem = "//*[text()='Xóa thành công']"
gstheotuyenmau_liscense_plate = "//*[@id='txtVehiclePlate']"
chidanduong_detail_fee = "//*[@id='findroad_bot_vehicletype']"
chuotphaimap_taovunglotrinh = "/html/body/div[21]/div[2]/div[2]/div[10]"
checkpopup_taovunglotrinh = "//*[@id='frmCreateSurround']//*[@class='float_left Header']"
taovunglotrinh_iconx = "//*[@id='frmCreateSurround']//*[@src='/Images/s_icon_x.png']"
chuotphaimap_timxetrongvung = "/html/body/div[21]/div[2]/div[2]/div[11]"
giamsat_diem2 = "//*[@src='https://gps.binhanh.vn/icons/point/19.png']"
check_timxetrongvung = "//*[@id='panelSearch']/div/div[2]/div/b"
chuotphaimap_timxegannhat = "/html/body/div[21]/div[2]/div[2]/div[12]"
checkpopup_timxegannhat = "//*[@id='panelSearchNearest']/div/div[2]/div/b"
chuotphaimap_cauhinhhienthinhomdiem = "/html/body/div[21]/div[2]/div[2]/div[14]"
cauhinhhienthinhomdiem_chuachonnhom = "//*[@id='divConfigGroupLandmark']/div[4]/input[1]"
cauhinhhienthinhomdiem_tramthuphi = "//*[@id='divConfigGroupLandmark']/div[4]/input[2]"
cauhinhhienthinhomdiem_hienthivungbao = "//*[@id='divConfigGroupLandmark']/div[5]/table/tbody/tr[3]/td/input"
cauhinhhienthinhomdiem_hienthitendiem = "//*[@id='divConfigGroupLandmark']/div[5]/table/tbody/tr[4]/td/input"
chuotphaimap_luuthongtinhienthi = "//*[@id='btnSaveConfigGroupLandmark']"
check_tramthuphi_vungbao = "/html/body/div[3]/form/div[3]/div[3]/div[8]/div[2]/div[3]//*[@fill-opacity='0.2']"
check_tramthuphi_tendiem = "//*[text()='Trạm thu phí Cao tốc Pháp Vân - Cầu Giẽ (Liên Ninh)']"
chuotphaimap_luuthongtinhienthi_ok = "//*[@data-bb-handler='ok']"
check_message_luucauhinhhienthi = "//*[@class='bootbox modal fade bootbox-alert in']/div/div/div[1]/div"
check_chuachonnhom_vungbao = "/html/body/div[3]/form/div[3]/div[3]/div[8]/div[2]/div[3]//*[@fill-opacity='0.5']"
check_chuachonnhom_tendiem = "//*[@class='leaflet-marker-icon custom-marker-leaflet leaflet-zoom-animated leaflet-interactive']//*[text()='Nhà của Trường1']"
chuotphaimap_cauhinhkhoidong = "/html/body/div[21]/div[2]/div[2]/div[15]"
check_popupcauhinhhienthibando = "//*[@id='frmConfigMap']//*[@class='float_left Header']"
cauhinhienthi_loaibando = "//*[@id='ddlMapType']"
cauhinhienthi_loaibando_vetinhbinhanh = "//*[@id='ddlMapType']//*[@value='5']"
cauhinhienthi_kinhdo = "//*[@id='txtLongitude']"
cauhinhienthi_vido = "//*[@id='txtLatitude']"
cauhinhienthi_muczoombando = "//*[@id='txtMapZoom']"
cauhinhienthi_luu = "//*[@id='btnSaveMapConfig']"
cauhinhienthi_huy = "//*[@id='btnCancelFormMapConfig']"
cauhinhienthi_loaibando_bando = "//*[@id='ddlMapType']//*[@value='2']"
chuotphaimap_bieudonhienlieumoi = "//*[@class='x-menu-bound-content-midd']//*[@style='height: 20px; float: left; background-color: rgb(255, 255, 255);']//*[text()='Biểu đồ nhiên liệu mới']"
check_popup_bieudonhienlieumoi = "//*[@class='bootbox modal fade bootbox-alert in']/div/div/div[1]/div"
chuotphaimap_gstheotuyenmau = "/html/body/div[21]/div[2]/div[2]/div[17]"
check_popup_gstheotuyenmau = "//*[@id='popUpBoxVehicleTrackingForm']/div/div[1]/div[2]"
chuotphaimap_gstheotuyenmau_iconx = "//*[@id='btnCloseVTWRForm']"
danhsachcongty = "//*[text()='Danh sách công ty']"
danhsachcongty_loai = "//*[@name='ctl00$ctl00$MainContent$Content$companySearch$ddlSearchType']"
danhsachcongty_loai_tencongty = "//*[@name='ctl00$ctl00$MainContent$Content$companySearch$ddlSearchType']//*[@value='2']"
danhsachcongty_noidung = "//*[@placeholder='Nội dung']"
danhsachcongty_timkiem = "//*[@id='btnSearch']"
check_timkiem_congty = "//*[@id='ctl00_ctl00_MainContent_Content_grvReport']/tbody/tr[2]/td[2]"
danhsachcongty_icondencongty = "//*[@src='../../Images/s_icon_GotoCompany.png']"
giamsat = "//*[@id='ModuleOnline']"
danhsachxe_dungtat = "//*[text()='Dừng - Tắt']"
chuotphaimap_dieuxedituyen = "/html/body/div[21]/div[2]/div[2]/div[19]"
check_popup_dieuxedituyen = "//*[@id='divVehicleOperator']/div[1]/div/div"
dieuxedituyen_tuyendichuyen = "//*[@id='txtRoute']"
dieuxedituyen_diemnhanhang = "//*[@id='txtRecive']"
dieuxedituyen_bienkiemsoat = "//*[@id='txtVehiclePlateOpertator']"
dieuxedituyen_ghichu = "//*[@id='txtNote']"
dieuxedituyen_sdtlaixe = "//*[@id='txtPhone']"
dieuxedituyen_laixe = "//*[@id='txtDriver']"
dieuxedituyen_luuvatieptuc = "//*[@id='btnaddVhOperatorCon']"
dieuxedituyen_themmoi = "//*[@id='btnaddVhOperator']"
dieuxedituyen_thoat = "//*[@id='btnCloseVhOperator']"
check_gs_timkiem_timxe = "//*[@class='leaflet-popup-content-wrapper']/div/div[3]/div[1]/div[2]"
timkiem_timxe_input1 = "//*[@id='toolbox']//*[@placeholder='Nhập xe cần tìm']"
check_gs_mauxe = "//*[@id='idClearOnline']/table/tbody/tr[1]"
check_gs_tendiem = "//*[@class='leaflet-popup-content-wrapper']/div/div/div[2]"
check_gs_timtoado_kinhdo = "//*[@class='leaflet-popup-content-wrapper']/div/div/div[5]"
check_gs_timtoado_vido = "//*[@class='leaflet-popup-content-wrapper']/div/div/div[8]"
tk_43e02740 = "//*[text()='43E02740 [950]']"
tongsoxe_duoi = "//*[@id='display_allsumvehicle']"
ungroup = "//*[text()='Không nhóm đội [1010]']"
ungroup_1 = "//*[text()='ungroup_1 [1010]']"
e43E02743 = "//*[text()='43E02743 [950]']"
trangthai_tatca = "//*[@id='ddlVehicleState']//*[@selected='selected']"
check_popup_hientranghethong = "//*[@id='panelStatus']/div/div[2]/b"
check_popup_ynghiabieutuongxe = "//*[@id='popUpBox_theMeaningOfIcon']//*[@class='float_left Header']"
nhapthongtinxe_x = "//*[@id='vehicleInfomation']//*[@id='imgClosevehicleInfo']"
popupthongtinxe_loaihinhvantai_vantaihanghoa = "//*[@id='vehicleInfomation']//*[@value='500']"
popupthongtinxe_vantaidangkychaynoithanh = "//*[@id='ctl00_MainContent_vehicleInfoBGT_ckCustomerInBGT']"
check_popupthongtinxe_loaihinhvantai = ""
popupthongtinxe_chopheptichtruyendulieu = "//*[@id='ctl00_MainContent_vehicleInfoBGT_ckBGTForward']"
check_popupthongtinxe_congty = "//*[@id='ctl00_MainContent_vehicleInfoBGT_ddlBranch_ddlBranch']/option[1]"
check_popupthongtinxe_trongtai = "//*[@id='ctl00_MainContent_vehicleInfoBGT_txtWeightBGT']"
popupthongtinxe_loaihinhvantai_xekhachtuyencodinh = "//*[@id='vehicleInfomation']//*[@value='100']"
danhsachxe_xe1 = "//*[@id='idClearOnline']/table/tbody/tr[1]"
popupthongtinxe_capnhat1 = "//*[@id='ctl00_MainContent_vehicleInfoBGT_BtnUpdate']"
check_giamsatnhieuxe_xe1 = "//*[@id='boxRight']/div[1]"
check_giamsatnhieuxe_xe3 = "//*[@id='boxRight']/div[3]"
hover_giamsat = "//*[@id='boxRight']/div[1]/div[6]"
hover_giamsat_phongto = "//*[@id='boxRight']/div[1]/div[6]/ul/li[2]"
check_giamsat_iconphongto = "//*[@class='c leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom']"
hover_giamsat_phongto_x = "//*[@class='dZoom']//*[@src='/icons/onlines/close.png']"
giamsatnhieuxe_iconx3 = "//*[@id='boxRight']/div[3]/div[5]"
giamsatnhieuxe_iconx2 = "//*[@id='boxRight']/div[2]/div[5]"
giamsatnhieuxe_iconx1 = "//*[@id='boxRight']/div[1]/div[5]"
check_danhsachxe_thongtinxe = "//*[@pid='panelTabNormal1']"
check_danhsachxe_hientrang_x = "//*[@class='leaflet-popup-close-button']"
hientrang_goicuoc = "//*[@pid='panelTabBacam1']"
check_popup_anxe = "//*[@id='panelHideVehicle']//*[@class='header-title']"
giamsat_anxe_dong = "//*[@id='panelHideVehicle']//*[text()='Đóng']"
danhsachxe_tenphuongtien1 = "//*[@id='idClearOnline']/table/tbody/tr[1]/td[2]/div[2]"
check_danhsachxedangan_trangthai = "//*[@id='panelFavourite']/div/div[8]/table/tbody/tr[1]/td[3]"
check_danhsachxedangan_truyentcdb = "//*[@id='panelFavourite']/div/div[8]/table/tbody/tr[1]/td[4]//*[@src='/Images/tick.gif']"
icon_danhsachxedangan_nguyennhan = "//*[@id='ddlErrorType']//*[@value='3']"
icon_danhsachxedangan_timkiem = "//*[@id='imgSearchVehicleInterest']"
check_capnhatxe_ghichu = "//*[@id='txtNoteErrorDetail']"
capnhatxe_antrengiamsat = "//*[@id='radHideTracking']"
luuvadungtruyen = "//*[@id='btnErrorSaveAndStopTransfer']"
icon_danhsachxedangan_x_tichtruyen = "//*[@class='btn btn-primary btn-transfer']"
check_xemhinhanhnhanh = "//*[@class='pp_content_container']"
xemhinhanhnhanh_dong = "//*[@class='pp_overlay']"
goto_43e02740 = "//*[text()='43E02740 [950]']"
check_xemanhcamera = "//*[@class='tableBoxHeader']"
check_popup_khoangcachdencacxe = "//*[@id='panelMeasureDistance']/div/div[2]/table/tbody/tr[1]/td[1]"
check_khoangcach = "//*[@class='float-left;']/table/tbody/tr[1]/td[2]/div[2]"
khoangcachdencacxe_tenxe1 = "//*[@class='searchMeasureContent']/tr[1]/td[2]/div"
khoangcachdencacxe_teninput = "//*[@id='filter_name']"
bieudoluuluong = "/html/body/div[20]/div[2]/div[2]/div[14]"
check_popup_bieudoluuluong = "//*[@id='popUpBoxFlow']//*[@class='float_left Header']"
bieudoluuluong_iconx = "//*[@id='popUpBoxFlow']//*[@id='btnCloseFlowChart']"
gstheotuyenmau = "/html/body/div[20]/div[2]/div[2]/div[18]"
gstheotuyenmau_iconx = "//*[@id='btnCloseVTWRForm']"
goto_nhapmaxninput = "//*[@placeholder='Nhập mã XN']"
goto_dencongty = "//*[@class='blog-info']//*[text()='Đến công ty']"
taonhanhdonhang = "/html/body/div[20]/div[2]/div[2]/div[19]"
check_popuptaonhanhdonhang = "//*[@class='modal_content popUpBox']/table[1]/tbody/tr[1]/td/div"
taonhanhdonhang_dong = "//*[@class='btn btn-primary btnCloseAddOrder']"
goto_1010congtykhongconhomdoi = "//*[text()='1010_Công ty không có nhóm đội [1010]']"
nhaplichchuyenxe = "/html/body/div[20]/div[2]/div[2]/div[20]"
check_popup_themmoichuyen = "//*[@id='divTripAdd']/div[1]/div/div/span"
nhaplichchuyenxe_dong = "//*[@id='divTripAdd']/div[3]/div/div/input[1]"
iconphuongtienthieuthongtintichtruyen = "//*[@src='/Images/Car.png']"
icontheodoichuyenhang = "//*[@title='Theo dõi chuyến hàng']"
icontheodoichuyenhang_ok = "//*[@class='bootbox modal fade bootbox-alert in']//*[@class='btn btn-primary']"
check_popuptheodoichuyenhang = "//*[@id='panelCpm']/div/div[2]/b"
icontheodoichuyenhang_x = "//*[@id='panelCpm']//*[@title='Đóng']"
iconxemanhcamera = "//*[@title='Xem ảnh Camera']"
check_popuphientranghethong = "//*[@id='panelStatus']/div/div[2]/b"
check_popupdanhsachxedangan = "//*[@id='panelFavourite']/div/div[2]"
danhsachxedangan_x = "//*[@id='panelFavourite']//*[@title='Đóng']"
check_popupdanhsachxe2g = "//*[@id='divListVehicle2G']/div[1]"
icon_danhsachxe2g = "//*[@title='Danh sách xe 2G và 3G']"
icon_canhbaotimeline = "//*[@title='Cảnh báo Timeline']"
check_popupcanhbaotimeline = "//*[@id='warningTimeline']/table/tbody/tr[1]/td[1]/div"
canhbaotimeline_x = "//*[@id='closeTimeline']"
iconthongtinxetoihandivaophocam = "//*[@title='Thông tin xe tới hạn đi vào phố cấm']"
iconcanhbaoxechuatoidiem = "//*[@title='Cảnh báo xe chưa tới điểm']"
# check_popupcanhbaoxechuatoidiem = "//*[@id='PanelDestinationAlertOnline']/div/div[2]/div[1]"
check_popupcanhbaoxechuatoidiem = "//*[@id='PanelDestinationAlertOnline']/div/div[3]/table/thead/tr[1]/th[1]"
canhbaoxechuatoidiem_x = "//*[@id='PanelDestinationAlertOnline']//*[@class='closeRightPanel']"
iconcanhbao = "//*[@title='Cảnh báo']"
check_popupcanhbao = "//*[@id='panelWarningOnline']/div/div[2]/div[1]"
popupthongtinxe_nomay = "//*[@id='panelTabNormal1']/div[1]/div[16]"
check_dokhoangcach = "//*[@id='divDistance']//*[@class='float_left Header']"
dokhoangcach_iconxoa = "//*[@id='imgDelete']"
dokhoangcach_iconx = "//*[@id='imgDistance']"
check_popup_dokhoangcach = "//*[text()='0.03 km']"
check_popupchihuong = "//*[@id='ds_ds']"
timxegannhat_xe1 = "//*[@id='tableVehicleSearchNearest']/tbody/tr[1]"
check_chihuong_diema = "//*[@class='undefined']//*[@src='/icons/DanDuong/diemdi.png']"
check_chihuong_diemb = "//*[@class='undefined']//*[@src='/icons/DanDuong/diemden.png']"
# check_chihuong_google = "//*[@src='//maps.gstatic.com/consumer/images/icons/1x/ic_directions_filled_blue900_24px.png']"
# check_chihuong_google =   "//*[@src='//maps.gstatic.com/consumer/images/icons/2x/ic_directions_filled_blue900_24px.png']"
check_chihuong_google = "//*[@class='FkdJRd vRIAEd dS8AEf']"
chihuong_icondoivitri2diem = "//*[@src='/icons/DanDuong/refresh.png']"
popupthongtinxe_dungxenomay = "//*[@id='panelTabNormal1']/div[1]/div[16]"
check_popupchidanduong = "//*[@id='findroad_landmark_tab']"
chidanduong_iconx = "//*[@id='findroad_btnExit']"
check_chidanduong_diemdi = "//*[@class='undefined']//*[@src='/icons/DanDuong/diemdi.png']"
check_chidanduong_diemden = "//*[@class='undefined']//*[@src='/icons/DanDuong/diemden.png']"
chidanduong_icondoivitri = "//*[@id='findroad_revert_btn']"
check_popuptimtheolotrinh = "//*[text()='Tìm theo lộ trình']"
danhsachxe_dichuyen = "//*[@id='td_movesumvehicle']"
timtheolotrinh_ngaybatdau = "//*[@id='findroad_fromDatePicker']"
check_timtheolotrinh_quangduong = "//*[@id='findroad_totaldistance']"
check_timtheolotrinh_changthuphi = "//*[@id='ds_ds_new']/div[3]/table/tbody/tr[12]/td/div[1]/table/tbody/tr[3]/td[2]"
check_timtheolotrinh_nhienlieudinhmuc = "//*[@id='ds_ds_new']/div[3]/table/tbody/tr[12]/td/div[1]/table/tbody/tr[3]/td[3]"
check_timtheolotrinh_chiphidukien = "//*[@id='findroad_totalcost']"
check_timtheolotrinh_tomtatlotrinh = "//*[@id='findroad_detailsroute_summary']"
check_popuptaodiem = "//*[@class='float_left Header addlandmarkHeader']"
taovunglotrinh_huy = "//*[@id='btCancel']"
close = "//*[@class='leaflet-popup-close-button']"
timxetrongvung_capnhatmoidulieu = "//*[@id='searchVehicleRefresh']"
timxetrongvung_ketxuat = "//*[@id='btnExportExcelSearch']"
timxetrongvung_iconx = "//*[@id='imageClose']"
giamsat_diem1 = "//*[@src='https://gps.binhanh.vn/icons/point/concrete_station.png']"
giamsat_diem3 = "//*[@src='https://gps.binhanh.vn/icons/point/recycle_bin_3.png']"
timxegannhat_iconx = "//*[@id='panelSearchNearest']//*[@title='Đóng']"
check_popupcauhinhhienthinhomdiem = "//*[@class='quantri-box popUpBox']//*[@class='float_left Header']"
chuotphaimap_cauhinhhienthinhomdiem_iconx = "//*[@class='quantri-box popUpBox']//*[@src='/Images/s_icon_x.png']"
chuotphaimap_cauhinhhienthinhomdiem_iconx1 = "//*[@id='frmConfigGroupLandmark']//*[@src='/Images/s_icon_x.png']"
check_messagetattatca = "//*[@class='bootbox-body']"
chuotphaimap_bieudonhienlieu = "//*[@class='x-menu-bound-content-midd']//*[@style='height: 20px; float: left; background-color: rgb(255, 255, 255);']//*[text()='Biểu đồ nhiên liệu']"
dieuxedicheck_popupdieuxedituyentuyen_thoat = "//*[@id='divVehicleOperator']/div[1]/div/div"
vehicle = "//*[@id='ModuleRoute']"
check_popup_route = "//*[@id='signinPanel']//*[@class='active']/a"
license_plates = "//*[@placeholder='Biển số']"
km_move = "//*[@id='TongKM']"
route_icondownloaddata = "//*[@id='btnGetData']"
check_iconprintroute = "//*[@id='btnPrint']"
check_printroute_licenseplate = "//*[@id='lblInfo']"
icon_downloadexcel = "//*[@id='btnExportExcel']"
khongcocamera = "//*[text()='Phương tiện không sử dụng camera video giám sát.']"
check_popuproute_loaddata = "//*[@id='list']/div[2]"
icon_runroute = "//*[@id='ViewRoute']"
check_timeroute = "//*[@id='idthoigian0']"
icon_dataconfig = "//*[@id='columnOption']"
checkpopup_dataconfig = "//*[@id='trVgps']/td[2]"
dataconfig_vgps = "//*[@id='chkVgps']"
dataconfig_vco = "//*[@id='chkCo']"
dataconfig_vbgt = "//*[@id='chkVbgt']"
dataconfig_km = "//*[@id='chkKm']"
dataconfig_displayfuel = "//*[@id='chkFuel']"
dataconfig_doorstatus = "//*[@id='chkCua']"
dataconfig_harmonicstatus = "//*[@id='chkDieuHoa']"
dataconfig_machinestatus = "//*[@id='chkMay']"
dataconfig_longitude_latitude = "//*[@id='chkLngLat']"
dataconfig_displayadress = "//*[@id='chkAddress']"
check_namecolumn_vgps = "//*[@id='idvantocgps']"
check_namecolumn_vco = "//*[@id='idvantocco']"
check_namecolumn_vbgt = "//*[@id='idvattocbgt']"
check_namecolumn_fuel = "//*[@id='idfuel']"
check_namecolumn_km = "//*[@id='idkm']"
check_namecolumn_door = "//*[@id='idcua']"
check_namecolumn_harmonic = "//*[@id='iddieuhoa']"
check_namecolumn_machine = "//*[@id='idmay']"
check_namecolumn_longitude_latitude = "//*[@id='idLngLat']"
check_namecolumn_adress = "//*[@id='idAddr']"
check_totalkm = "//*[@id='TongKM']"
icon_route_display_config = "//*[@title='Cấu hình hiển thị lộ trình']"
checkpopup_routedisplayconfig = "//*[@id='divListConfigViewRoute']//*[@class='float_left Header']"
icon_route_display_config_cancel = "//*[@id='divListConfigViewRoute']//*[@id='btCancel']"
route_liscense_plate = "//*[@id='divListConfigViewRoute']//*[@id='txtVehiclePlate']"
combined_parking = "//*[@id='chkGroupRecord']"
note_lost_signal = "//*[@id='chkStateSignalLoss']"
stoptime = "//*[@id='lblTimeStopOff']"
lost_signal_time = "//*[@id='trTimeSignalLoss']/td[1]/label"
defaultconfig = "//*[@id='divListConfigViewRoute']//*[@id='Button1']"
routedisplayconfig_save = "//*[@id='divListConfigViewRoute']//*[@id='btnSave']"
managerment = "//*[@id='ModuleAdmin']"
type_vehicle = "//*[@id='column-right']//*[@id='VEHICLETYPEMANAGER']"
name_typevehicle1 = "//*[@class='table table-bordered']/tbody/tr[2]/td[2]/span"
typevehicle_search = "//*[@placeholder='Nhập loại phương tiện để tra cứu']"
typevehicle_buttonsearch = "//*[@class='btn btn-primary cssBtnSearch']"
check_page_type_vehicle = "//*[@class='tableBoxHeader']"
managerment_typevehicle = "//*[@id='column-right']//*[@id='VEHICLETYPEMANAGER']"
typevehicle_addnew = "//*[@id='column-right']//*[@class='btn btn-primary btnAdd']"
typevehicle = "//*[@id='txtVhType']"
number_of_seats = "//*[@id='txtWeightSeat']"
km_maintenance = "//*[@id='txtQuotaKm']"
addnew_license_plates = "//*[@id='txtVehicles']"
addnew_infovehicle_buttonsave = "//*[@id='divInsertUpdate']//*[@value='Lưu']"
save_successfully = "//*[text()='Thêm mới thành công']"
check_typevehicle = "//*[@class='table table-bordered']/tbody/tr[6]/td[2]/span"
check_typevehicle_icondelete = "//*[@class='table table-bordered']/tbody/tr[6]/td[7]"
type_vehicle_iconprint = "//*[@src='/images/s_icon_print.png']"
checkpopup_print = "//*[@title='In báo cáo']"
type_vehicle_iconprint_x = "//*[@title='Đóng']"
type_vehicle_downloadexcel = "//*[@src='/images/excel.gif']"
check_downloadexcel = "//*[text()='Đang tiến hành tạo file Excel. Vui lòng không thoát trang, tìm kiếm lại... cho đến khi file được tải về máy']"
type_vehicle_downloadpdf = "//*[@src='/images/s_icon_pdf.png']"
check_typevehicle_edit = "//*[@class='table table-bordered']/tbody/tr[2]/td[6]"
check_edit = "//*[@id='divInsertUpdate']/div[1]/div/div"
check_typevehicle_edit_exit = "//*[@id='divInsertUpdate']//*[@value='Thoát']"
list_vehicle = "//*[@id='masterTwoColumnRight']//*[@id='AdminListOfVehicle']"
check_listvehicle = "//*[@class='tableBoxHeader']"
list_vehicle_buttonsearch = "//*[@class='btn btn-primary cssbtnSearch']"
name_vehicle1 = "//*[@id='upGrid']/div/table/tbody/tr[2]/td[10]/a/b"
liscense_plate = "//*[@placeholder='Nhập biển kiểm soát hỗ trợ ']"
write_info_vehicle = "//*[text()='Nhập nhanh thông tin xe']"
select_file = "//*[@id='btnFileUpload']"
upload = "//*[@value='Tải lên']"
check_write_info_vehicle = "//*[text()='Cập nhật thông tin xe thành công']"
button_write_information = "//*[@id='ctl00_ctl00_MainContent_Content_btnImportInfoVehicle']"
button_back = "//*[@id='ctl00_ctl00_MainContent_Content_btnBack']"
search_user_information = "//*[text()='Tra cứu người dùng']"
check_search_user_information = "//*[@class='tableBoxBordered']//*[@class='tableBoxHeader']"
assign_vehicle = "//*[@id='column-right']//*[@id='AdminAssignVehicle']"
icon_gotocompany = "//*[@class='table table-bordered']/tbody/tr[2]//*[@title='Đến công ty']"
check_goto_company = "//*[@title='Công ty goto đến']"
gotocompany_exit = "//*[@title='Thoát khỏi chế độ goto company']"
list_vehicle1 = "//*[@class='leftMenuContainer']//*[@id='AdminListOfVehicle']"
icon_assign_car = "//*[@class='table table-bordered']/tbody/tr[2]//*[@title='Gán xe']"
check_assign_car = "//*[text()='Lưu thành công']"
assign_car_user1 = "//*[@class='tableBox']/tbody/tr[4]/td/div/div[1]/div/ul/li/div/ul/li[1]/div/input"
assign_car_group1 = "//*[@class='tableBox']/tbody/tr[5]/td/div/div[1]/div/ul/li/div/ul/li[1]/div/input"
history_imei = "//*[@id='ctl00_ctl00_MainContent_Content_btnSearchHistoryImei']"
assign_car = "//*[@id='ctl00_ctl00_MainContent_Content_btnApproveImei']"
icon_look_user_manage = "//*[@class='table table-bordered']/tbody/tr[2]//*[@title='Gán người dùng']"
icon_hide_car = "//*[@class='table table-bordered']/tbody/tr[2]//*[@title='Ẩn xe']"
check_hide_car = "//*[@class='table table-bordered']/tbody/tr[2]//*[@title='Bỏ ẩn xe']"
open_the_car_quickly = "//*[@class='table table-bordered']/tbody/tr[2]//*[@title='Mở xe nhanh']"
check_open_car_quickly = "//*[text()='Mở xe thành công']"
icon_display_info_car = "//*[@class='table table-bordered']/tbody/tr[2]//*[@title='Thông tin đồng bộ BAP']"
check_popup_display_info_car = "//*[@id='divfrmInfoBap']//*[@id='ctl00_ctl00_MainContent_Content_frmInfoBap_modal_ctl00']"
popup_display_info_car_close = "//*[@id='divfrmInfoBap']//*[@value='Đóng']"
list_vehicle_advanced_search = "//*[text()='Tìm kiếm nâng cao']"
select_hide_car = "/html/body/div[3]/form/div[3]/div[3]/table/tbody/tr/td[3]/div/div/table/tbody/tr[7]/td/div/div[2]/div/div/div[2]/div[5]/div[2]/div/a"
select_hide1 = "//*[@class='chzn-drop']/ul//*[text()='Xe GPS  lỗi']"
check_look_user_manage = "//*[@class='table table-bordered']/tbody/tr[2]/td[3]"
check_advanced_search = "//*[@id='ctl00_ctl00_MainContent_Content_advanceSearch']/tbody/tr[2]/td[3]"
# assign_car_select_company1 = "//*[@class='tableBox']/tbody/tr[3]/td/div/div/ul/li[2]"
assign_car_select_company1 = "/html/body/div[3]/form/div[3]/div[3]/table/tbody/tr[1]/td[3]/div/div[2]/table/tbody/tr[3]/td/table/tbody/tr/td[1]/fieldset/table/tbody/tr[3]/td/div/div/ul/li[2]"
assign_car_select_company = "//*[@class='tableBox']/tbody/tr[3]/td/div/a"
assign_car_select_car = "//*[@class='tableBox']/tbody/tr[2]/td/div/a"
# assign_car_select_car1 = "//*[@class='tableBox']/tbody/tr[2]/td/div/div/ul/li[2]"
assign_car_select_car1 = "/html/body/div[3]/form/div[3]/div[3]/table/tbody/tr[1]/td[3]/div/div[2]/table/tbody/tr[3]/td/table/tbody/tr/td[1]/fieldset/table/tbody/tr[2]/td/select/option[2]"
assign_car_select_input = "//*[@id='ctl00_ctl00_MainContent_Content_ddlVehiclePlate_chzn']//*[@class='chzn-search']/input"
assign_car_select_input2 = "//*[@id='ctl00_ctl00_MainContent_Content_ddlCompany_chzn']//*[@class='chzn-search']/input"
other = "//*[text()='KHÁC']"
admin_group = "//*[@class='leftMenuContainer']//*[@id='AdminGroupVehicle']"
admin_group_search = "//*[@placeholder='Nhập biển kiểm soát tìm kiếm']"
check_admin_group = "//*[@id='masterTwoColumnRight']//*[@class='tableBoxHeader']"
admin_group_buttonsearch = "//*[@id='masterTwoColumnRight']//*[@value='Tìm kiếm']"
check_admin_group_search = "//*[@id='masterTwoColumnRight']//*[@class='table table-bordered']/tbody/tr[2]/td[2]"
name_group = "//*[@id='masterTwoColumnRight']//*[@id='divCreateGroup']/table/tbody/tr[2]/td[1]/div[1]/div/ul/li[1]"
icon_addgroup_level1 = "//*[@id='AddNewRootGroup']"
namegroup_level1 = "//*[@id='divJsTree']//*[text()='nhóm bậc 1']"
icon_addgroup_level1_input = "//*[@class='jstree-rename-input']"
addgroup_addnew = "//*[@id='AddNewGroup']"
namegroup_leveln = "//*[@id='divJsTree']//*[text()='nhóm bậc n']"
delete_group = "//*[@id='DeleteGroup']"
namegroup_editedgroup = "//*[@id='divJsTree']//*[text()='nhóm smile home']"
namegroup_nhomtest = "//*[@id='divJsTree']//*[text()='nhóm test']"
mark_special_groups = "//*[@id='btnmark']"
check_icon_mark = "//*[@id='divJsTree']//*[@src='/Images/clock.png']"
un_mark_special_groups = "//*[@id='btnunmark']"
list_car_1 = "//*[@id='lstAllVehicle']/option[1]"
icon_assign_car3 = "//*[@id='btnMoveLeft']"
list_group_car_1 = "//*[@id='lstAssignedVehicle']/option[1]"
icon_assign_car2 = "//*[@id='btnMoveRight']"
icon_assign_car4 = "//*[@id='btnMoveAllLeft']"
list_group_car_3 = "//*[@id='lstAssignedVehicle']/option[3]"
icon_assign_car1 = "//*[@id='btnMoveAllRight']"
vehicle_groups_administration = "//*[@class='leftMenuContainer']//*[@id='AdminPermissionUserVehicleGroups']"
check_vehicle_groups_administration = "//*[@class='masterTwoColumnRight']//*[@class='tableBoxHeader']"
vehicle_groups_administration_search = "//*[@placeholder='Nhập biển kiểm soát tìm kiếm']"
check_vehicle_groups_administration_search = "//*[@id='lstUser']/option[1]"
vehicle_groups_administration_buttonsearch = "//*[@id='btnSearch']"
list_user_company_truongtest = "//*[@id='lstUser']//*[text()='truongtest1-TRẦN QUANG TRƯỜNG']"
list_groupcar_company1 = "//*[@id='jtreeNoAssign']/ul/li[1]/a/ins[1]"
icon_assign_group2 = "//*[@id='btnMoveRight']"
list_group_user1 = "//*[@id='jtreeAssigned']/ul/li[1]/a/ins[1]"
icon_assign_group3 = "//*[@id='btnMoveLeft']"
icon_assign_group1 = "//*[@id='btnMoveRight_All']"
list_group_user3 = "//*[@id='jtreeAssigned']/ul/li[3]/a/ins[1]"
icon_assign_group4 = "//*[@id='btnMoveLeft_All']"
list_user = "//*[@class='leftMenu']//*[@id='AdminListOfUser']"
list_user_nameuser = "//*[@class='table table-bordered']/tbody/tr[2]/td[2]/a"
list_user_search_input = "//*[@placeholder='Nhập nội dung cần tìm']"
list_user_icon_downloadexcel = "//*[@title='Xuất Excel']"
managerment_report = "//*[@id='ModuleReports']"
activity_synthesis_report = "//*[@class='masterTwoColumnRight']//*[@id='ReportActivitySummaryNew']"
check_activity_synthesis_report = "//*[@class='tableBoxHeader']"
activity_synthesis_report_search = "//*[@id='ctl00_ctl00_MainContent_Content_btnSearch']"
check_activity_synthesis_report_search = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]"
downloadexcel = "//*[@title='Xuất Excel']"
detailed_activity_report = "//*[@class='leftMenu']//*[@id='ReportActivityDetail']"
check_detailed_activity_report = "//*[@class='column-right']//*[@class='tableBoxHeader']"
detailed_activity_report_mergeminute = "//*[@class='column-right']//*[@id='ctl00_ctl00_MainContent_Content_cbGroup']"
check_detailed_activity_report_mergeminute = "//*[@class='column-right']//*[text()='Số phút giới hạn']"
detailed_activity_report_timeslot = "//*[@class='column-right']//*[@id='chkKhungGio']"
check_detailed_activity_report_timeslot = "//*[@class='column-right']//*[text()='Khung giờ xuất báo cáo']"
detailed_activity_report_search = "//*[@class='column-right']//*[@id='ctl00_ctl00_MainContent_Content_btnSearch']"
check_detailed_activity_report_search = "//*[@class='column-right']//*[text()='STT']"
detailed_activity_report_from_date = "//*[@id='ctl00_ctl00_MainContent_Content_dtFromDate_txtDate']"
report_km_activity_summary = "//*[@class='leftMenu']//*[@id='REPORTACTIVITYSUMMARYKM']"
check_report_km_activity_summary = "//*[@class='column-right']//*[@class='tableBoxHeader']"
report_km_activity_summary_detail = "//*[@id='ctl00_ctl00_MainContent_Content_rblSummaryDetail_0']"
report_km_activity_summary_search = "//*[@id='ctl00_ctl00_MainContent_Content_btnSearch']"
check_report_km_activity_summary_detail = "//*[@class='table-report']/tbody/tr[1]/th[1]"
report_km_activity_summary_summary = "//*[@id='ctl00_ctl00_MainContent_Content_rblSummaryDetail_1']"
stop_report = "//*[@class='leftMenu']//*[@id='ReportStop']"
stop_report_fromdate_input = "//*[@id='column-right']//*[@id='ctl00_ctl00_MainContent_Content_dtFromDate_txtDate']"
activity_synthesis_group_report_fromdate_input = "//*[@id='ctl00_ctl00_MainContent_Content_dtFromDate_txtDate']"
report_km_activity_summary_from_date = "//*[@id='ctl00_ctl00_MainContent_Content_dtFromDate_txtDate']"
report_search = "//*[@id='ctl00_ctl00_MainContent_Content_btnSearch']"
fromdate_input = "//*[@id='ctl00_ctl00_MainContent_Content_dtFromDate_txtDate']"
report_business_trip = "//*[@class='leftMenuContainer']//*[@id='ReportBusinessTrip']"
station_report = "//*[@class='leftMenu']//*[@id='ReportStation']"
report_air_conditioner_summaries = "//*[@class='leftMenu']//*[@id='ReportAirConditionerSummaries']"
machine_report = "//*[@class='leftMenu']//*[@id='REPORTMACHINE']"
position_history = "//*[@class='leftMenu']//*[@id='ReportItinerary']"
check_position_history_time_slot = "//*[@id='ctl00_ctl00_MainContent_Content_lblKhungGioXuat']"
position_history_choose_car3rd = "//*[@id='ctl00_ctl00_MainContent_Content_vehicleAutoComplete_ddlVehiclePlate_chzn']//*[@class='chzn-results']/li[3]"
position_history_time_slot = "//*[@id='chkKhungGio']"
position_history_choose_car = "//*[@id='ctl00_ctl00_MainContent_Content_vehicleAutoComplete_ddlVehiclePlate_chzn']//*[@class='chzn-single']"
check_position_history_search = "//*[@id='divItinerary']"
fuel_consumption_summary_report = "//*[@class='leftMenu']//*[@id='FuelConsumptionSummary']"
fuel_consumption_daily_report = "//*[@class='leftMenu']//*[@id='FUELCONSUMPTIONDAILY']"
report_pour_fuel = "//*[@class='leftMenu']//*[@id='ReportPourFuel']"
device_singnal_report = "//*[@class='leftMenu']//*[@id='ReportSignalLoss']"
check_report_search = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]"
report_speed_over = "//*[@class='leftMenu']//*[@id='ReportSpeedOver']"
report_checkin_checkout = "//*[@class='leftMenu']//*[@id='CheckInCheckOutSummaries']"
speed_over_report = "//*[@class='leftMenu']//*[@id='ReportQCVN31SpeedOver']"
report_BGT = "//*[@id='ModuleBGTReports']"
videoclip = "//*[@id='CameraImage']"
playbackvideo_overview = "//*[@class='leftMenuContainer']//*[@id='VideoReviewOverview']"
check_playbackvideo_overview = "//*[@class='vr-tbl-tt-tt']"
playbackvideo_selecgroup = "//*[@id='videoReviewWrapper']/table[1]/tbody/tr[3]/td/div/div[1]/button"
playbackvideo_namegroup = "//*[@id='videoReviewWrapper']/table[1]/tbody/tr[3]/td/div/div[1]/div/ul/li[2]/label"
playbackvideo_selecgroup_input = "//*[@id='videoReviewWrapper']/table[1]/tbody/tr[3]/td/div/div[1]/div/div/input"
playbackvideo_selecgroup1 = "//*[@id='videoReviewWrapper']/table[1]/tbody/tr[3]/td/div/div[1]/div/ul/li[2]/label/input"
playbackvideo_findvehicle = "//*[@id='videoReviewWrapper']/table[1]/tbody/tr[3]/td/div/div[2]/button"
playbackvideo_findvehicle1 = "//*[@id='videoReviewWrapper']/table[1]/tbody/tr[3]/td/div/div[2]/div/ul/li[2]/label/input"
playbackvideo_buttonsearch = "//*[@class='btnButton btn btn-search btn-primary vr-tbl-sr-btnSearch']"
# name_vehicle = "//*[@id='videoReviewWrapper']/table[1]/tbody/tr[3]/td/div/div[1]/div/ul/li[2]/label"
name_vehicle = "//*[@id='videoReviewTable']/tbody/tr[3]/td/div/div[2]/button/span"

check_playbackvideo_overview_search = "//*[@class='vr-timeline-tbl-div-w']/div/table/tbody/tr[3]/td[2]"
playbackvideo_detail = "//*[@class='leftMenuContainer']//*[@id='VIDEOREVIEWDETAIL2']"
playbackvideo_detail_selectgroup = "//*[@class='tblVehicleVideo-body-center-search']/div[1]/div/button"
playbackvideo_detail_selectgroup1 = "//*[@class='tblVehicleVideo-body-center-search']/div[1]/div/div/ul/li[2]/label/input"
playbackvideo_detail_selectvehicle = "//*[@class='tblVehicleVideo-body-center-search']/div[2]/div/button"
playbackvideo_detail_selectvehicle1 = "//*[@class='tblVehicleVideo-body-center-search']/div[2]/div/div/ul/li[2]/label/input"
playbackvideo_detail_search = "//*[@value='Tìm kiếm']"
playbackvideo_detail_name_vehicle = "//*[@id='videoReviewTable']/tbody/tr[2]/td/div/table/tbody/tr/td/div/div[2]/div[1]/div[2]/div/button/span"
# playbackvideo_detail_name_vehicle = "//*[@class='tblVehicleVideo-body-center-search']/div[1]/div/div/ul/li[2]/label"
check_playbackvideo_detail_search = "//*[@class='vr-timeline-tr vr-timeline-tr-content-vehicle vr-timeline-tr-content']/td[1]"
playbackvideo_detail_view_multi_chanel = "//*[text()='Xem nhiều kênh']"
check_playbackvideo_detail_view_multi_chanel = "//*[@id='divMessageVideo2']"
check_cam_tracking = "//*[@class='tv-fs-tblv1-title']"
cam_tracking = "//*[@class='leftMenu']//*[@id='TrackingVideo']"
cam_tracking_icon_watch_vehicle1 = "//*[@class='tv-fs-tblv1-lm-listVehicle']/div[3]/div[1]/div[2]/img"
cam_tracking_icon_watch_vehicle2 = "//*[@class='tv-fs-tblv1-lm-listVehicle']/div[3]/div[2]/div[2]/img"
cam_tracking_icon_watch_vehicle3 = "//*[@class='tv-fs-tblv1-lm-listVehicle']/div[3]/div[3]/div[2]/img"
check_cam_tracking_icon_watch_vehicle = "//*[@id='video-panel-9']"
cam_tracking_downloadexcel = "//*[@title='Xuất excel danh sách xe']"
cam_tracking_select_group = "//*[@class='panel-left panel-left-show']/table/tbody/tr[2]/td/div/button"
cam_tracking_select_group1 = "//*[@class='panel-left panel-left-show']/table/tbody/tr[2]/td/div/div/ul/li[2]/label/input"
cam_tracking_find_vehicle = "//*[@class='panel-left panel-left-show']/table/tbody/tr[3]/td/div/button"
cam_tracking_find_vehicle1 = "//*[@class='panel-left panel-left-show']/table/tbody/tr[3]/td/div/div/ul/li[2]/label/input"
cam_tracking_status = "//*[@class='panel-left panel-left-show']/table/tbody/tr[4]/td/select"
cam_tracking_status1 = "//*[@class='panel-left panel-left-show']/table/tbody/tr[4]/td/select/option[2]"
cam_tracking_select_place = "//*[@class='panel-left panel-left-show']/table/tbody/tr[5]/td/div/button"
cam_tracking_select_place1 = "//*[@class='panel-left panel-left-show']/table/tbody/tr[5]/td/div/div/ul/li[1]/label/input"
cam_tracking_status_chanel = "//*[@class='panel-left panel-left-show']/table/tbody/tr[6]/td/select"
cam_tracking_status_chanel1 = "//*[@class='panel-left panel-left-show']/table/tbody/tr[6]/td/select/option[2]"
name_cam_tracking_find_vehicle = "//*[@class='panel-left panel-left-show']/table/tbody/tr[3]/td/div/button/span"
check_cam_tracking_search = "//*[@class='panel-left panel-left-show']/table/tbody/tr[8]/td/div/div/div[3]/div[1]/div[1]/label"
image = "//*[@id='ImageND10']"
tracking_by_images = "//*[@class='leftMenuContainer']//*[@id='TrackingVehiclesByImage']"
check_tracking_by_images = "//*[@class='pageTitle']"
tracking_by_images_watch_image = "//*[@id='vehicles']/div[1]/div[2]/div[1]/div[1]/img"
check_tracking_by_images_watch_image = "//*[@id='vehicleDetail']/div[1]/div/div/div/img"
tracking_by_images_watch_image_iconx = "//*[@class='close1']"
tracking_by_images_selecgroup = "//*[@class='tv-fs-tblv1-lm']/tbody/tr[2]/td/div/button"
tracking_by_images_selecgroup1 = "//*[@class='tv-fs-tblv1-lm']/tbody/tr[2]/td/div/div/ul/li[2]/label/input"
tracking_by_images_findvehicle = "//*[@class='tv-fs-tblv1-lm']/tbody/tr[3]/td/div/button"
tracking_by_images_findvehicle1 = "//*[@class='tv-fs-tblv1-lm']/tbody/tr[3]/td/div/div/ul/li[2]/label/input"
tracking_by_images_name_vehicle = "//*[@class='tv-fs-tblv1-lm']/tbody/tr[3]/td/div/button/span"
check_tracking_by_images_search = "//*[@class='tv-fs-tblv1-lm-listVehicle']/tbody/tr[1]/td[2]/div"
tracking_vehicle_by_images_online = "//*[@class='leftMenuContainer']//*[@id='TrackingVehiclesByImageOnline']"
tracking_vehicle_by_images_online_watch_image = "//*[@id='vehicles']/div[1]/div[1]/div[2]/img"
check_tracking_vehicle_by_images_online_search = "//*[@class='tv-fs-tblv1-lm-listVehicle']/div[3]/div/div[1]/label"
tracking_single_vehicle = "//*[@class='leftMenuContainer']//*[@id='TrackingVehiclesByImageSingle']"
check_tracking_single_vehicle = "//*[@class='vr-tbl-tt-tt']"
tracking_single_vehicle_selecgroup = "//*[@class='search-field']/input"
tracking_single_vehicle_selecgroup1 = "//*[@class='chzn-drop']/ul/li[1]"
tracking_single_vehicle_chosevehicle = "//*[@id='ddlVehicles_chzn']/a"
tracking_single_vehicle_chosevehicle1 = "//*[@id='ddlVehicles_chzn']/div/ul/li[2]"
tracking_single_vehicle_name_vehicle = "//*[@id='ddlVehicles_chzn']/a/span"
check_tracking_single_vehicle_search = "//*[@id='galery-image']/div[1]/div[1]/img"
tracking_single_vehicle_search = "//*[@alt='search']"
camera_image_management = "//*[@class='leftMenuContainer']//*[@id='ImageManagementMND10']"
check_camera_image_management = "//*[@class='tableBoxHeader']"
camera_image_management_selecgroup = "//*[@id='ctl00_ctl00_MainContent_Content_vehicleAutoComplete_ddlVehicleGroup_chzn']//*[@class='chzn-single']"
camera_image_management_selecgroup1 = "//*[@id='ctl00_ctl00_MainContent_Content_vehicleAutoComplete_ddlVehicleGroup_chzn']/div/ul/li[2]"
camera_image_management_chanel = "//*[@class='ms-parent']/button"
camera_image_management_chanel1 = "//*[@class='ms-parent']/div/ul/li[1]/label/input"
camera_image_management_chosevehicle = "//*[@id='ctl00_ctl00_MainContent_Content_vehicleAutoComplete_ddlVehiclePlate_chzn']//*[@class='chzn-single']"
camera_image_management_chosevehicle1 = "//*[@id='ctl00_ctl00_MainContent_Content_vehicleAutoComplete_ddlVehiclePlate_chzn']/div/ul/li[2]"
camera_image_management_name_vehicle = "//*[@id='ctl00_ctl00_MainContent_Content_vehicleAutoComplete_ddlVehiclePlate_chzn']/a/span"
camera_image_management_search = "//*[@id='ctl00_ctl00_MainContent_Content_btnSearch']"
check_camera_image_management_search = "//*[@class='tableBoxBordered']/tbody/tr[7]/td/table/tbody/tr[1]/td/div/div[1]/div/a/img"
camera_image_management_watch_image_iconx = "//*[@id='lightbox-secNav-btnClose']"
view_camera_photos = "//*[@class='leftMenuContainer']//*[@id='ImageViewMND10']"
check_view_camera_photos_search = "//*[@id='tableContainer']/tbody/tr[7]/td/table/tbody/tr[1]/td[1]/table/tbody/tr/td[2]/div/table/tbody/tr[2]/td/div/table/tbody/tr[1]/td[1]"
view_camera_photos_search1 = "//*[@class='lstImage']/table/tbody/tr[1]"
view_camera_photos_search2 = "//*[@class='lstImage']/table/tbody/tr[2]"
check_canhbao_xemanhcamera = "//*[@class='tableBoxHeader']"
iconxemanhcamera_x = "//*[@id='panelImageOnline']//*[@src='/Images/s_icon_x.png']"
admin_utility = "//*[@id='ModuleUtilities']"
device_info = "//*[@class='leftMenu']//*[@id='AdminUtilityDeviceInfo']"
check_device_info = "//*[@id='column-right']//*[@class='tableBoxHeader']"
device_info_name_liscense2 = "//*[@id='ctl00_ctl00_MainContent_Content_grvDeviceInfo']/tbody/tr[2]/td[2]"
device_info_input = "//*[@placeholder='Nhập nội dung cần tìm']"
device_info_buttonsearch = "//*[@id='ctl00_ctl00_MainContent_Content_btnSearch']"
check_device_info_search = "//*[@id='ctl00_ctl00_MainContent_Content_grvDeviceInfo']/tbody/tr[1]/td[2]/div"
device_info_device_info = "//*[@id='idDeviceInfo']"
landmark_administraintion = "//*[@id='masterTwoColumnRight']//*[@id='AdminNewLandmark']"
check_landmark_administraintion = "//*[@class='tabbable utracking-control']/ul/li[1]/a"
landmark_administraintion_place_search_input = "//*[@placeholder='Nhập địa chỉ cần tìm']"
landmark_administraintion_place_buttonsearch = "//*[@id='ctl00_MainContent_PointCategoryList_btnSearch']"
check_landmark_administraintion_place_search = "//*[text()='Tính năng không được hỗ trợ.']"
landmark_administraintion_place_search = "//*[@class='nav nav-tabs']/li[2]/a"
landmark_administraintion_searchinput = "//*[@id='txtSearchLandmarks']"
check_landmark_administraintion_search_nameplace = "//*[@class='font_tahoma_11px']/tbody/tr[4]/td/div/ul/li[1]/ul/li[1]/a"
landmark_administraintion_search_adressplace = "//*[@id='rad2']"
check_landmark_administraintion_search_adressplace = "//*[@class='font_tahoma_11px']/tbody/tr[4]/td/div/ul/li[1]/ul/li[1]/a"
landmark_administraintion_search_buttonsearch = "//*[@class='font_tahoma_11px']//*[@value='Tìm kiếm']"
landmark_group = "//*[@id='masterTwoColumnRight']//*[@id='AdminConfigurationLandmark']"
check_landmark_group = "//*[@id='UC_LandmarksGroup']/table/tbody/tr[1]/td[2]/div[2]"
landmark_group_addnewplace_input = "//*[@id='txtLandmarksGroupName']"
landmark_group_addnewplace = "//*[@id='ctl00_ctl00_MainContent_Content_UCLandmarkGroup_btnAdd']"
nhomdiemz = "//*[@id='lstLandmarksGroup']//*[text()='nhom diem z']"
landmark_group_update = "//*[@id='ctl00_ctl00_MainContent_Content_UCLandmarkGroup_btnSave']"
nhomdiemzupdate = "//*[@id='lstLandmarksGroup']//*[text()='nhom diem z da sua']"
landmark_group_delete = "//*[@id='ctl00_ctl00_MainContent_Content_UCLandmarkGroup_btnDelete']"
nhomdiemb = "//*[@id='lstLandmarksGroup']//*[text()='nhom diem b']"
point_do_not_assigned = "//*[@id='radPointNo']"
point_in_landmarks_group = "//*[@id='radPointAs']"
company_gtel = "//*[@id='lstLandmarks']//*[text()='Gtel']"
landmark_group_iconright = "//*[@id='btnRight']"
group_gtel = "//*[@id='lstLandmarksAssigned']//*[text()='Gtel']"
landmark_group_iconleft = "//*[@id='btnLeft']"
landmark_group_name_place2 = "//*[@id='lstLandmarks']/option[2]"
landmark_group_input = "//*[@id='txtSearch']"
landmark_group_buttonsearch = "//*[@id='ctl00_ctl00_MainContent_Content_UCLandmarkGroup_btnSearch']"
check_landmark_group_search = "//*[@id='lstLandmarks']/option[1]"
landmark_group_administration = "//*[@class='leftMenu']//*[@id='AdminGroupLandmark']"
check_landmark_group_administration = "//*[@id='column-right']//*[@class='tableBoxHeader']"
check_landmark_group_administration_create_user = "//*[@id='column-right']//*[@class='tableBoxHeader']"
landmark_group_administration_create_user = "//*[@id='ctl00_ctl00_MainContent_Content_lnkCreateUser']"
landmark_group_administration_create_landmarks_group = "//*[@id='ctl00_ctl00_MainContent_Content_lnkCreatGroup']"
landmark_group_administration_truongvck1 = "//*[@id='ctl00_ctl00_MainContent_Content_UCAssignPermissionLmGroupForUser1_lstUser']//*[text()='truongvck1-TRẦN QUANG TRƯỜNG']"
company_nhomdiema = "//*[@id='ctl00_ctl00_MainContent_Content_UCAssignPermissionLmGroupForUser1_lstLandmarksGroup']//*[text()='nhom diem a']"
landmark_group_administration_icon1right = "//*[@id='ctl00_ctl00_MainContent_Content_UCAssignPermissionLmGroupForUser1_btnRight']"
check_landmark_group_administration_assign_1group = "//*[@id='ctl00_ctl00_MainContent_Content_UCAssignPermissionLmGroupForUser1_lstLandmarksGroupUser']//*[text()='nhom diem a']"
landmark_group_administration_icon1left = "//*[@id='ctl00_ctl00_MainContent_Content_UCAssignPermissionLmGroupForUser1_btnLeft']"
landmark_group_administration_iconmanyright = "//*[@id='ctl00_ctl00_MainContent_Content_UCAssignPermissionLmGroupForUser1_btnRightAll']"
check_landmark_group_administration_assign_many_group = "//*[@id='ctl00_ctl00_MainContent_Content_UCAssignPermissionLmGroupForUser1_lstLandmarksGroupUser']//*[text()='nhom diem b']"
landmark_group_administration_iconmanyleft = "//*[@id='ctl00_ctl00_MainContent_Content_UCAssignPermissionLmGroupForUser1_btnLeftAll']"
landmark_group_administration_nguyenthuhuong = "//*[@id='ctl00_ctl00_MainContent_Content_UCAssignPermissionLmGroupForUser1_lstUser']//*[text()='huongnt24-Nguyễn Thu Hương']"
add_landmarks_quickly = "//*[@class='leftMenu']//*[@id='QuickImports']"
check_add_landmarks_quickly = "//*[@id='column-right']//*[@class='tableBoxHeader']"
add_landmarks_quickly_downloadexcel = "//*[@id='ctl00_ctl00_MainContent_Content_btnGetFile']"
add_landmarks_quickly_choosefile = "//*[@id='btnFileUpload']"
add_landmarks_quickly_uploadfile = "//*[@id='ctl00_ctl00_MainContent_Content_fileUploader1_btnUpload']"
check_add_landmarks_quickly_uploadfile = "//*[@class='table table-bordered']/tbody/tr[2]/td[2]"
add_landmarks_quickly_add_quickly = "//*[@id='ctl00_ctl00_MainContent_Content_btnImportInfoSIM']"
check_add_landmarks_quickly_add_quickly = "//*[text()='Dòng 1: Tên điểm đã trùng']"
point_in_displayed_place = "//*[@id='chkLableInfoPoint']"
ai = "//*[@id='AiCam']"
summary_report_of_driving_behavior = "//*[@class='overView']//*[@id='AiReportDriverActivitySummary']"
check_summary_report_of_driving_behavior = "//*[@class='content-right-header text-primary']"
summary_report_of_driving_behavior_checkgotocompnay = "//*[text()=' Công ty: CÔNG TY TNHH ĐIỀN LINH - 2415 - ctydienlinh ']"
check_report_driving_violations = "//*[@class='form-title']"
report_driving_violations = "//*[@class='leftMenuContainer']//*[@id='AICamReportDriver']"
driving_rating_report = "//*[@class='leftMenuContainer']//*[@id='AiReportDriverRankMonth']"
list_user_icon_pdf = "//*[@id='ReportExportPDF']"
list_user_print = "//*[@id='ReportPrintReport']"
check_list_user_print = "/html/body/div[1]/div[3]"
list_user_print_iconx = "//*[@title='Đóng']"
list_user_column = "//*[@id='ReportAddRemoveColumns']"
list_user_column_cancel = "//*[@id='ctl00_ctl00_MainContent_Content_btnCancel']"
list_user_create = "//*[@class='tableBoxBordered']//*[text()='Thêm mới']"
check_list_user_create = "//*[@id='column-right']//*[@class='tableBoxHeader']"
list_user_permission = "//*[@class='table table-bordered']/tbody/tr[2]/td[7]//*[@src='/Images/s_icon_editRolePermission.png']"
check_list_user_permission = "//*[@id='column-right']//*[@class='tableBoxHeader']"
list_user_lock = "//*[@class='table table-bordered']/tbody/tr[2]//*[@src='/Images/unlock.png']"
check_list_user_lock = "//*[text()='Khóa tài khoản thành công']"
check_list_user_unlock = "//*[text()='Mở khóa tài khoản thành công']"
list_user_unlock = "//*[@class='table table-bordered']/tbody/tr[2]//*[@src='/Images/lock.png']"
list_user_search = "//*[@id='ctl00_ctl00_MainContent_Content_btnSearch']"
list_user_reset_password = "//*[@class='table table-bordered']/tbody/tr[2]//*[@src='../../Images/edit_item.png']"
check_list_user_reset_password = "//*[text()='Khởi tạo lại mật khẩu thành công']"
list_user_reset_change_password = "//*[@class='table table-bordered']/tbody/tr[2]//*[@src='../../Images/s_icon_editUserPermission.png']"
check_list_user_reset_change_password = "//*[@id='column-right']//*[@class='tableBoxHeader']"
nodata = "//*[@id='ctl00_ctl00_MainContent_Content_grvReport_NoDataImage']"
list_user_reset_copy_acount = "//*[@class='table table-bordered']/tbody/tr[2]//*[@src='../../Images/copy_item.png']"
copy_acount_user = "//*[@id='ctl00_ctl00_MainContent_Content_frmCopy_modal_ctl06_txtUserName']"
copy_acount_name = "//*[@id='ctl00_ctl00_MainContent_Content_frmCopy_modal_ctl06_txtFullName']"
copy_acount_phonenumber = "//*[@id='ctl00_ctl00_MainContent_Content_frmCopy_modal_ctl06_txtPhoneNumberUserAdd']"
copy_acount_email = "//*[@id='ctl00_ctl00_MainContent_Content_frmCopy_modal_ctl06_txtEmail']"
copy_acount_password = "//*[@id='ctl00_ctl00_MainContent_Content_frmCopy_modal_ctl06_txtPassword']"
copy_acount_repeatpassword = "//*[@id='ctl00_ctl00_MainContent_Content_frmCopy_modal_ctl06_txtRePassword']"
copy_acount_typeaccount = "//*[@id='cbkUserType_1']"
copy_acount_save = "//*[@id='ctl00_ctl00_MainContent_Content_frmCopy_modal_ctl07_btnSaveCreate']"
check_list_user_reset_copy_acount = "//*[text()='Lưu thành công']"
list_user_reset_delete = "//*[@class='table table-bordered']/tbody/tr[2]//*[@src='/Images/delete_item.png']"
check_list_user_reset_delete = "//*[text()='Xóa tài khoản thành công']"
check_giamsat = "//*[text()='Tổng số xe']"
list_user_permanently_deleted = "//*[@class='table table-bordered']/tbody/tr[2]//*[@src='/icons/Point/recycle_bin_1.png']"
check_list_user_list_user_permanently_deleted = "//*[text()='Xóa tài khoản thành công']"
list_user_unlock_login = "//*[@class='table table-bordered']/tbody/tr[2]//*[@src='/Images/user_unlock.png']"
check_list_user_unlock_login = "//*[@id='ctl00_ctl00_MainContent_Content_MessageContainer_MessageContainer']"
list_user_logout_account = "//*[@class='table table-bordered']/tbody/tr[2]//*[@src='/Images/s_icon_GotoCompany.png']"
check_list_user_logout_account = "//*[text()='Đăng xuất tất cả thiết bị thành công']"
list_user_name1 = "//*[@class='table table-bordered']/tbody/tr[2]/td[2]/a"
playbackvideo_detail_nodata = "//*[@id='capturOutputImg']"
playbackvideo_detail_selectvehicle2 = "//*[@class='tblVehicleVideo-body-center-search']/div[2]/div/div/ul/li[3]/label/input"
playbackvideo_detail_selectvehicle3 = "//*[@class='tblVehicleVideo-body-center-search']/div[2]/div/div/ul/li[4]/label/input"
playbackvideo_detail_selectvehicle4 = "//*[@class='tblVehicleVideo-body-center-search']/div[2]/div/div/ul/li[5]/label/input"
playbackvideo_detail_selectvehicle_span = "//*[@class='tblVehicleVideo-body-center-search']/div[2]/div/button/span"
check_playbackvideo_detail = "//*[@class='customtab-list-video-panel-1 customtab-list-video-panel customtab-list-video-panel-active']/div[1]"
exit = "//*[@id='ctl00_ctl00_MainContent_Content__frmInsertUpdate_modal_ctl07_btnClose']"
save_already_exist = "//*[text()='Loại phương tiện đã tồn tại']"
check_login_v2sai = "//*[text()='Trần Quang Trường PQA']"
todate_input = "//*[@id='ctl00_ctl00_MainContent_Content_dtToDate_txtDate']"
admin_group_nhombacn = "//*[@id='divCreateGroup']//*[text()='nhóm bậc n']"
admin_group_nhombac1 = "//*[@id='divCreateGroup']//*[text()='nhóm bậc 1']"
ctyanhngocminh = "//*[text()='ctyanhngocminh [7669]']"
truonganphat = "//*[text()='Công ty TNHH MTV XDTM và DVVT Trường An Phát [7669]']"
cttoancau = "//*[text()='Công ty TNHH Dịch vụ Tiếp Vận Toàn Cầu (GLS) [71097]']"
tranquocdungdn = "//*[text()='Trần Quốc Dũng [71097]']"
group_d = "//*[@id='lstLandmarksGroup']//*[text()='nhom diem d']"
check_user = "//*[@id='ctl00_ctl00_MainContent_Content_companySearch_ddlSearchType']/option[3]"
check_company = "//*[@id='ctl00_ctl00_MainContent_Content_companySearch_ddlSearchType']/option[1]"
check_phuongtienthieuthongtintichtruyen = "//*[@class='btn-close btn-close-page']"
check_thongtinxetoihandivaophocam = "/html/body/div[26]/div/div/div[1]/div"
icon_canhbaotimeline_iconx = "/html/body/div[26]/div/div/div[2]/button"

info_vehicle_line1 = "//*[@id='panelTabNormal1']/div[1]/div[1]"
info_vehicle_line2 = "//*[@id='panelTabNormal1']/div[1]/div[2]"
info_vehicle_line3 = "//*[@id='panelTabNormal1']/div[1]/div[3]"
check_popup_battatnhomdiemgannhau = "//*[text()='Lưu thông tin thành công. Trang hiện tại sẽ tự động load lại để áp dụng các thay đổi sau vài giây nữa.']"
activity_synthesis_group_report_day_month = "//*[@id='divTable']/table/tbody/tr[4]/td[4]"
activity_synthesis_group_report_time_from = "//*[@id='divTable']/table/tbody/tr[4]/td[5]"
activity_synthesis_group_report_time_to = "//*[@id='divTable']/table/tbody/tr[4]/td[6]"
activity_synthesis_group_report_from_address = "//*[@id='divTable']/table/tbody/tr[4]/td[7]"
activity_synthesis_group_report_to_address = "//*[@id='divTable']/table/tbody/tr[4]/td[8]"
activity_synthesis_group_report_time_run = "//*[@id='divTable']/table/tbody/tr[4]/td[9]"
activity_synthesis_group_report_percent_run = "//*[@id='divTable']/table/tbody/tr[4]/td[10]"
activity_synthesis_group_report_time_stop = "//*[@id='divTable']/table/tbody/tr[4]/td[11]"

activity_synthesis_group_report_km_gps = "//*[@id='divTable']/table/tbody/tr[4]/td[14]"
activity_synthesis_group_report_km_engine = "//*[@id='divTable']/table/tbody/tr[4]/td[15]"
activity_synthesis_group_report_fuel_1km = "//*[@id='divTable']/table/tbody/tr[4]/td[17]"
activity_synthesis_group_report_fuel_consume = "//*[@id='divTable']/table/tbody/tr[4]/td[18]"
activity_synthesis_group_report_number_of_stop = "//*[@id='divTable']/table/tbody/tr[4]/td[19]"
activity_synthesis_group_report_turn_on_air_conditional = "//*[@id='divTable']/table/tbody/tr[4]/td[25]"
activity_synthesis_group_report_max_speed = "//*[@id='divTable']/table/tbody/tr[4]/td[26]"
activity_synthesis_group_report_average_speed = "//*[@id='divTable']/table/tbody/tr[4]/td[27]"
activity_synthesis_group_report_violate_continue = "//*[@id='divTable']/table/tbody/tr[4]/td[30]"
activity_synthesis_group_report_increase_speed1 = "//*[@id='divTable']/table/tbody/tr[4]/td[31]"
activity_synthesis_group_report_increase_speed2 = "//*[@id='divTable']/table/tbody/tr[4]/td[32]"
activity_synthesis_group_report_violate_too_speed = "//*[@id='divTable']/table/tbody/tr[4]/td[33]"
activity_synthesis_group_report_detail = "//*[@id='divTable']/table/tbody/tr[4]/td[34]"
activity_synthesis_group_report_route1 = "//*[@id='divTable']/table/tbody/tr[4]/td[35]"
activity_synthesis_group_report_route2 = "//*[@id='divTable']/table/tbody/tr[4]/td[36]"
activity_synthesis_group_report_stop = "//*[@id='divTable']/table/tbody/tr[4]/td[37]"

detailed_activity_report_type_vehicle = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
detailed_activity_report_license_plate = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
detailed_activity_report_group = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
detailed_activity_report_day_month = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
detailed_activity_report_from_hour = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
detailed_activity_report_to_hour = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
detailed_activity_report_start_liters = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"
detailed_activity_report_end_liters = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[9]"
detailed_activity_report_time_hd = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[10]"
detailed_activity_report_km_gps = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[11]"
detailed_activity_report_km_co = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[12]"
detailed_activity_report_fuel_1km = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[13]"
detailed_activity_report_fuel1 = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[14]"
detailed_activity_report_fuel2 = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[15]"
detailed_activity_report_from_address = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[16]"
detailed_activity_report_to_address = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[17]"
detailed_activity_report_note = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[18]"
detailed_activity_report_route = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[19]"
report_km_activity_summary_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
report_km_activity_summary_liscense_plate = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
report_km_activity_summary_type_vehicle = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
report_km_activity_summary_kmgps = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
report_km_activity_summary_kmco = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
report_km_activity_summary_time_on = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
report_km_activity_summary_time_off = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"

report_km_activity_summary_detail_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
report_km_activity_summary_detail_liscense_plate = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
report_km_activity_summary_detail_group = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
report_km_activity_summary_detail_day_moth = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
report_km_activity_summary_detail_type_vehicle = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
report_km_activity_summary_detail_customer = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
report_km_activity_summary_detail_km_gps = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
report_km_activity_summary_detail_km_co = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"
report_km_activity_summary_detail_time_on = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[9]"
report_km_activity_summary_detail_time_off = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[10]"
report_km_activity_summary_detail_detail = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[11]"

stop_report_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
stop_report_liscense_plate = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
stop_report_group = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
stop_report_name_driver = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
stop_report_staff_code = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
stop_report_phone_number = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
stop_report_time = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
stop_report_time_minute = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"
stop_report_time_stop = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[9]"
stop_report_turn_on_stop = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[10]"
stop_report_turn_on_air_condition_stop = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[11]"
stop_report_fuel = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[12]"
stop_report_temperature = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[13]"
stop_report_address = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[14]"
stop_report_titude_latitude_longitude = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[15]"
stop_report_note = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[16]"
stop_report_route = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[17]"
stop_report_video = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[18]/a/img"

report_business_trip_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
report_business_trip_type_vehicle = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
report_business_trip_liscense_plate = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
report_business_trip_group = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
report_business_trip_from_addres = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
report_business_trip_to_addres = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
report_business_trip_from_hour = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
report_business_trip_to_hour = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"
report_business_trip_time_active = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[9]"
report_business_trip_km_gps = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[10]"
report_business_trip_v_hanhtrinh = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[11]"
report_business_trip_v_average = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[12]"
report_business_trip_km_co = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[13]"
report_business_trip_fuel_start = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[14]"
report_business_trip_fuel_end = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[15]"
report_business_trip_fuel1 = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[16]"
report_business_trip_fuel2 = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[17]"
report_business_trip_fuel3 = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[18]"
report_business_trip_time_in_place_from = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[19]"
report_business_trip_time_in_place_to = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[20]"
report_business_trip_time_stop = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[21]"
report_business_trip_turn_air_conditional = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[22]"
report_business_trip_route = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[23]"

station_report_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
station_report_type_vehicle = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
station_report_liscense_plate = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
station_report_group = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
station_report_in_station = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
station_report_out_station = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
station_report_name_station = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
station_report_time_station = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"
station_report_route = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[9]"
station_report_linkvideo = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[10]/div/a/img"

report_air_conditioner_summaries_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
report_air_conditioner_summaries_liscense_plate = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
report_air_conditioner_summaries_from_day = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
report_air_conditioner_summaries_to_day = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
report_air_conditioner_summaries_summary_on_time = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
report_air_conditioner_summaries_number_stop_on_air_conditonal = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
report_air_conditioner_summaries_number_stop_lit_air_conditonal = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
report_air_conditioner_summaries_detail = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"



machine_report_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
machine_report_liscense_plate = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
machine_report_group = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
machine_report_start_time = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
machine_report_time = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
machine_report_to_time = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
machine_report_start_address = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
machine_report_end_address = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"
machine_report_route = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[9]"
position_history_vehicle = "//*[@id='ctl00_ctl00_MainContent_Content_vehicleAutoComplete_ddlVehiclePlate_chzn']/a/span"

fuel_consumption_summary_report_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
fuel_consumption_summary_report_group = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
fuel_consumption_summary_report_liscense_plate = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
fuel_consumption_summary_report_type_vehicle = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
fuel_consumption_summary_report_time_run = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
fuel_consumption_summary_report_time_stop = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
fuel_consumption_summary_report_number_stop = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
fuel_consumption_summary_report_number_of_suction = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"
fuel_consumption_summary_report_so_lit_dau_ky = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[9]"
fuel_consumption_summary_report_so_lit_do = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[10]"
fuel_consumption_summary_report_so_lit_hut = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[11]"
fuel_consumption_summary_report_so_lit_cuoi_ky = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[12]"
fuel_consumption_summary_report_nl_tieu_thu_dinh_muc = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[13]"
fuel_consumption_summary_report_nl_tieu_thu_thuc_te = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[14]"
fuel_consumption_summary_report_dinh_muc_quy_dinh = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[15]"
fuel_consumption_summary_report_dinh_muc_thuc_te = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[16]"
fuel_consumption_summary_report_dinh_muc_thuc_te_dung_do = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[17]"
fuel_consumption_summary_report_tong_km = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[18]"
fuel_consumption_summary_report_km_co = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[19]"
fuel_consumption_summary_report_ghi_chu1 = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[20]"
fuel_consumption_summary_report_ghi_chu2 = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[21]"
fuel_consumption_summary_report_chi_tiet = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[22]"
chuotphaimap_clearpopup1 = "/html/body/div[24]/div/div/div[1]/button"
chuotphaimap_clearpopup2 = "/html/body/div[3]/form/div[3]/div[3]/div[10]/div/table/thead/tr/td/div[2]/a[2]/img"
chuotphaimap_clearpopup3 = "/html/body/div[24]/div[2]/a[1]"
chuotphaimap_clearpopup4 = "/html/body/div[25]/div[2]/button"
chuotphaimap_clearpopup5 = "/html/body/div[3]/form/div[3]/div[3]/div[16]/form/div/table/tbody/tr/td/div/div[3]/a/img"
chuotphaimap_clearpopup6 = "/html/body/div[3]/form/div[3]/div[3]/div[17]/form/div/table/tbody/tr/td/div/div[3]/a/img"
chuotphaimap_clearpopup7 = "/html/body/div[3]/form/div[3]/div[3]/div[4]/div[5]/div/div[2]/span[1]/a/img"
chuotphaimap_clearpopup8 = "/html/body/div[3]/form/div[3]/div[3]/div[4]/div[6]/div/div[2]/span/a/img"
chuotphaimap_clearpopup9 = "/html/body/div[24]/div/div/div[1]/button"
chuotphaimap_clearpopup10 = "/html/body/div[3]/form/div[3]/div[3]/div[18]/form/div/div/div[3]/a/img"
chuotphaimap_clearpopup11 = "/html/body/div[3]/form/div[3]/div[3]/div[15]/form/div/table/tbody/tr/td/div/div[3]/a/img"
chuotphaimap_clearpopup12 = "/html/body/div[3]/form/div[3]/div[3]/div[25]/form/div/div/div[1]/div[3]/a/img"
chuotphaimap_clearpopup13 = "/html/body/div[3]/form/div[3]/div[3]/div[1]/div/div[1]/a"

fuel_consumption_daily_report_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
fuel_consumption_daily_report_ngaythang = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
fuel_consumption_daily_report_bienkiemsoat = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
fuel_consumption_daily_report_loaiphuongtien = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
fuel_consumption_daily_report_batdaudichuyen = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
fuel_consumption_daily_report_ketthucdichuyen = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
fuel_consumption_daily_report_thoigianlanbanh = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
fuel_consumption_daily_report_thoigiandungdonomay = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"
fuel_consumption_daily_report_solando = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[9]"
fuel_consumption_daily_report_solanhut = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[10]"
fuel_consumption_daily_report_solitdaungay = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[11]"
fuel_consumption_daily_report_solitdo = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[12]"
fuel_consumption_daily_report_solithut = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[13]"
fuel_consumption_daily_report_solitton = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[14]"
fuel_consumption_daily_report_nhienlieutieuhao = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[15]"
fuel_consumption_daily_report_dinhmucquydinh = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[16]"
fuel_consumption_daily_report_dinhmucthuctetheokm = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[17]"
fuel_consumption_daily_report_dinhmucthuctedungdonomay = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[18]"
fuel_consumption_daily_report_sotien = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[19]"
fuel_consumption_daily_report_km_gps = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[20]"
fuel_consumption_daily_report_bieudo = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[21]/img"
fuel_consumption_daily_report_lotrinh = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[22]"

report_pour_fuel_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
report_pour_fuel_bienkiemsoat = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
report_pour_fuel_thoigian = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
report_pour_fuel_solittruoc = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
report_pour_fuel_solit = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
report_pour_fuel_solitsau = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
report_pour_fuel_sotien = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
report_pour_fuel_diachi = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"
report_pour_fuel_ghichu = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[9]"
report_pour_fuel_lotrinh = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[10]"
report_pour_fuel_bieudo = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[11]/img"
report_pour_fuel_xoa = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[1]/th[12]"

device_singnal_report_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
device_singnal_report_bienkiemsoat = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
device_singnal_report_nhom = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
device_singnal_report_thoidiembatdau = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
device_singnal_report_thoidiemketthuc = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
device_singnal_report_thoigian = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
device_singnal_report_diadiembatdau = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
device_singnal_report_diadiemketthuc = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"
device_singnal_report_trangthai = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[9]"
device_singnal_report_lotrinh = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[10]"

report_speed_over_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
report_speed_over_bienkiemsoat = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
report_speed_over_thoidiem = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
report_speed_over_thoigian = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
report_speed_over_quangduong = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
report_speed_over_tocdocucdai = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
report_speed_over_diadiembatdau = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
report_speed_over_diadiemketthuc = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"
report_speed_over_ghichu = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[9]"
report_speed_over_bando = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[10]"

report_checkin_checkout_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
report_checkin_checkout_laixe = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
report_checkin_checkout_gplx = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
report_checkin_checkout_bienkiemsoat = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
report_checkin_checkout_dangnhap = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
report_checkin_checkout_dangxuat = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
report_checkin_checkout_solandangnhap = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
report_checkin_checkout_solandangxuat = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"
report_checkin_checkout_tongsolan = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[9]"


speed_over_report_stt = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[1]"
speed_over_report_biensoxe = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[2]"
speed_over_report_hotenlaixe = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[3]"
speed_over_report_sogiaypheplaixe = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[4]"
speed_over_report_loaihinhvandong = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[5]"
speed_over_report_thoidiem = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[6]"
speed_over_report_tocdotrungbinhkhiquagioiohan = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[7]"
speed_over_report_tocdogioihan = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[8]"
speed_over_report_tocdoquagioiohan = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[9]"
speed_over_report_diadiemquatocdogioihan = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[10]"
speed_over_report_ghichu = "//*[@id='ctl00_ctl00_MainContent_Content_ScrollPanel']/div/table/tbody/tr[2]/td[11]"
icon_hide_column = "//*[@alt='Add Column']"
activity_synthesis_group_repor_checkbox_daymoth = "//*[@id='divCheckboxList']/div[1]/input"
hide_column_cancel = "//*[@value='Hủy']"
detailed_activity_report_checkbox_typevehicle = "//*[@id='ctl00_ctl00_MainContent_Content_chkReportColumns_0']"
hide_column_cancel1 = "//*[text()='Hủy']"
report_km_activity_summary_checkbox_groupvehicle = "//*[@id='ctl00_ctl00_MainContent_Content_chkReportColumns_0']"
checkbox_groupvehicle = "//*[@id='ctl00_ctl00_MainContent_Content_chkReportColumns_0']"
checkbox_typevehicle = "//*[@id='ctl00_ctl00_MainContent_Content_chkReportColumns_0']"
position_history_hide_map = "//*[@title='Zoom out']"
# check_chihuong_diema = "//*[@class='leaflet-marker-icon custom-marker-leaflet leaflet-zoom-animated leaflet-interactive']//*[@src='/icons/DanDuong/diemdi.png']"
icon_hide_map = "//*[text()='Hiện/ ẩn bản đồ']"
check_fill_info_vehicle = "//*[text()='Đến trang khai báo TCĐB']"
check_hientrang = "//*[@class='leaflet-popup  leaflet-zoom-animated']"
check_chuotphaixe_anxe = "//*[@id='panelHideVehicle']"
check_thongtinthietbi = "//*[@class='ui-dialog ui-widget ui-widget-content ui-corner-all ui-draggable']"
check_bieudonhienlieu = "//*[@id='popUpBox']"
check_bieudonhienlieumoi = "//*[@id='divFuelChartNew']"
check_bieudonhietdo = "//*[@class='bootbox modal fade bootbox-alert in']"







