from selenium.webdriver.common.by import By
#trình duyệt 2
import openpyxl
import chucnangkhac

from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
capa = DesiredCapabilities.CHROME
capa["pageLoadStrategy"] = "none"
from seleniumwire import webdriver
driver = webdriver.Chrome(desired_capabilities=capa)
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('window-size=1920x1480')




# PATH ="C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/chromedriver.exe"
# path_baocao = "C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/GPS_ChecklistForAutoTest.xlsx"
# path_luutamthoi = "C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/bangluudulieu_tamthoi.xlsx"


def readData(file,sheetName,rownum,columnno):
    wordbook = openpyxl.load_workbook(file)
    sheet = wordbook.get_sheet_by_name(sheetName)
    return sheet.cell(row=rownum,column=columnno).value

def writeData(file,sheetName,rowum,columnno,data):
    wordbook = openpyxl.load_workbook(file)
    sheet = wordbook.get_sheet_by_name(sheetName)
    sheet.cell(row=rowum,column=columnno).value = data
    wordbook.save(file)


#đọc file config
f = open("file_config.txt", 'r')
for x in f:
     if x[0:11] == "- ModeTest:":   #1,2,3,4
         modetest = x[13:-2]
         # print(modetest)
     if x[0:11] == "- LinkTest:":   #https://gps.binhanh.vn
         linktest = x[13:-2]
     if x[0:10] == "- TimeRun:":    #09:41
         timerun = x[12:-2]
     if x[0:10] == "- LogPath:":    #C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/ba.log
         logpath = x[12:-2]
     if x[0:16] == "- CheckListPath:":  #C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/GPS_ChecklistForAutoTest_1.xlsx
         checklistpath = x[18:-2]
     if x[0:12] == "- ImagePath:":  #C:/Users/truongtq.BA/PycharmProjects/pythonProject/anhchup
         imagepath = x[14:-2]
     if x[0:15] == "- DataTestPath:":   #C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/data_ba.json
         datatestpath = x[17:-2]
     if x[0:13] == "- UploadPath:":     #C:/Users/truongtq.BA/PycharmProjects/pythonProject/file
         uploadpath = x[15:-2]
     if x[0:23] == "- LuuDuLieuTamThoiPath:":   #C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/bangluudulieu_tamthoi.xlsx
         path_luutamthoi = x[25:-2]
     if x[0:12] == "- ExcelPath:":      #C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/excel
         excelpath = x[14:-2]
     if x[0:13] == "- PathDriver:":     #C:/Users/truongtq.BA/PycharmProjects/pythonProject/ba_v2/chromedriver.exe
         PATH = x[15:-2]
     if x[0:13] == "- ModuleTest:":     #0,1,2,3,4
         moduletest = x[15:-2]





login_user = "//*[@placeholder='Tên đăng nhập']"
login_password = "//*[@placeholder='Mật khẩu']"
login_ghinhodangnhap = "//*[@checked='checked']"
dangnhap = "//*[@id='UserLogin1_btnLogin']"

icon_bagps = "//*[@id='imgLogo']"
check_loginsai = "//*[text()='Tên đăng nhập hoặc mật khẩu không hợp lệ.']"
login_iconappstore = "//*[@src='/Images/Login/iconLogin/SVG/photo_logo-IOS.svg']"
check_login_appstore = "//*[text()='BA GPS']"

hopthoai = By.XPATH, "//*[@class='chat-list custom-scroll']//*[text()='Cảnh báo Autotest BA_GPS V2']"
hopthoai_input = By.XPATH, "//*[@id='editable-message-text']"
hopthoai_iconlink = By.XPATH, "//*[@class='icon icon-attach']"
hopthoai_iconlink_file = By.XPATH, "//*[@id='attach-menu-controls']/div/div[2]//*[@class='icon icon-document']"
hopthoai_send = By.XPATH, "//*[@class='modal-dialog']/div[2]//*[text()='Send']"
login_iconchplay = "//*[@src='/Images/Login/iconLogin/SVG/photo_logo-android.svg']"
login_icontrangchu = "//*[@src='../../Images/Login/iconLogin/SVG/ic_home.svg']"
login_iconlienhezalo = "//*[@id='lnkCallZalo']"
login_iconzalo_x = "//*[@src='../../Images/X.png']"
login_iconsodienthoai = "//*[@src='../../Images/Login/iconLogin/png-phone-icon-13.jpg']"
login_bagps = "//*[@id='lnkGlobal']"
login_hotlinemuahang = "//*[text()='HOTLINE MUA HÀNG']"
login_muasamsanpham = "//*[text()='MUA SẮM SẢN PHẨM']"
login_thongtingiaiphap = "//*[text()='THÔNG TIN GIẢI PHÁP']"
check_login_lienhezalo = "//*[@class='contactzalo-header']"
check_login_trangchu = "//*[@class='row align-items-center col-mar-5']/div[1]/a/img"
check_login_chplay = "//*[text()='BA GPS']"
check_login_muasamsanpham = "//*[text()='Sản phẩm ']"
login_vechungtoi = "//*[text()='VỀ CHÚNG TÔI']"
check_login_vechungtoi = "//*[@class='about-1 bg']/div/div[1]/div[1]/h1"
login_mangluoi = "//*[text()='MẠNG LƯỚI']"
check_login_mangluoi = "//*[@class='q-main-page']/div/h1"
login_huongdansudung = "//*[text()='HƯỚNG DẪN SỬ DỤNG']"
check_login_huongdansudung = "//*[@id='channel-container']//*[text()='BA GPS']"
login_huongdandongphi = "//*[text()='HƯỚNG DẪN ĐÓNG PHÍ']"
check_login_huongdandongphi = "//*[@class='q-main-page v2 q-bg-gray']/div/div/div[1]/div/div[1]//*[text()='Hướng dẫn đóng phí dịch vụ BA GPS']"
linklienket_hopthoaizalo = "//*[@class='zalo-chat-widget']/iframe"
tiengviet = "/html/body/div/div[1]/div[1]/div/div/div[3]/div/div/div/div[1]"
english = "//*[@class='box-wrapper']//*[@class='zbtn zbtn-clear']"
chatnhanh = "//*[text()='Chat nhanh']"
hopthoaizalo_dau3cham = "//*[@class='far fa-ellipsis-h']"
hopthoaizalo_ketthuccuoctrochuyen = "//*[text()='Kết thúc cuộc trò chuyện']"
hopthoaizalo_icondong = "//*[@class='fal fa-chevron-down']"
check_login_iconzalo_doingonngu = "//*[@class='box__welcome']/h1"
check_login_iconzalo_chatnhanh = "//*[text()='Xin chào! BA GPS rất vui được hỗ trợ bạn.']"
iconngonngu_tienganh = "//*[@id='header-authentication']/div[3]/a//*[@src='/icons/flags/110-united%20kingdom.png']"
taikhoan = "//*[@id='header-authentication']//*[@id='lblAccount']"
dangxuat = "//*[text()='Đăng xuất']"
check_login_giamsat = "//*[@id='master-menu']//*[text()='Giám sát']"
check_login_khac = "//*[@id='master-menu']//*[text()='KHÁC']"
check_login_quantri = "//*[@id='master-menu']//*[text()='Quản trị']"


##GIÁM SÁT
menu_giamsat = "//*[@id='master-menu']//*[text()='Giám sát']"
timkiem_icon = "//*[@class='SearchSelect']"
timkiem_icon_timxe = "//*[@id='SelectSearchType']//*[@id='liVehicle']"
timkiem_icon_timdiachi = "//*[@id='SelectSearchType']//*[@id='liAddress']"
timkiem_icon_tendiem = "//*[@id='SelectSearchType']//*[@id='liLandmarkName']"
timkiem_icon_timtoado = "//*[@id='SelectSearchType']//*[@id='liLatLng']"
timkiem_timxe_input = "//*[@placeholder='Biển kiểm soát']"
timkiem_iconsearch = "//*[@id='SearchBtn']"
danhsachxe_tenphuongtien = "//*[@id='idClearOnline']/table/tbody/tr[1]/td[2]/div[2]"
saved = "//*[text()=' Saved ']"
timkiem_tendiem_input = "//*[@placeholder='Tên điểm']"
danhsachxe_tendiem = "//*[@class='ui-autocomplete ui-menu ui-widget ui-widget-content ui-corner-all']/li[1]/a"
timkiem_icon1 = "//*[@class='SearchSelect Landmark LandmarkName']"
timkiem_timtoado_input = "//*[@placeholder='Tọa độ']"
nhomxe = "//*[@id='ddlVehicleGroup']"
chonnhomxe1 = "//*[@id='ddlVehicleGroup']/option[2]"
bienso1 = "//*[@id='tblVehicleList']/tbody/tr[1]/td[2]/div[2]"
tatcanhomxe = "//*[@id='ddlVehicleGroup']//*[text()='Tất cả']"
trangthai = "//*[@id='ddlVehicleState']"
trangthai_batmay1 = "//*[@id='ddlVehicleState']//*[@value='1']"
checkiconxe_batmay1 = "//*[@id='tblVehicleList']/tbody/tr[2]/td[2]/div[1]/img"
soluong_dungbat = "//*[@id='tr_ColorSumVehicle']/td/table/tbody/tr[1]/td[2]/div"
soluong_dichuyen = "//*[@id='tr_ColorSumVehicle']/td/table/tbody/tr[1]/td[3]/div"
soluong_quatocdo = "//*[@id='tr_ColorSumVehicle']/td/table/tbody/tr[1]/td[4]/div"
tongsoxe_tren = "//*[@id='tr_ColorSumVehicle']/td/table/tbody/tr[1]/td[6]/div/div[1]"
trangthai_tatmay1 = "//*[@id='ddlVehicleState']//*[@value='2']"
soluong_dungtat = "//*[@id='tr_ColorSumVehicle']/td/table/tbody/tr[1]/td[1]/div"
trangthai_quatocdo = "//*[@id='ddlVehicleState']//*[@value='10']"
trangthai_dungdo = "//*[@id='ddlVehicleState']//*[@value='4']"
trangthai_dichuyen = "//*[@id='ddlVehicleState']//*[@value='3']"
trangthai_tatmay2 = "//*[@id='ddlVehicleState']//*[@value='8']"
trangthai_batmay2 = "//*[@id='ddlVehicleState']//*[@value='9']"
trangthai_mattinhieu = "//*[@id='ddlVehicleState']//*[@value='5']"
soluong_mattinhieu = "//*[@id='tr_ColorSumVehicle']/td/table/tbody/tr[1]/td[5]/div"
icon_xuatexcel = "//*[@class='tab-content']//*[@src='/Images/s_icon_excelExport.png']"
icon_capnhatdulieu = "//*[@class='tab-content']//*[@title='Cập nhật mới dữ liệu']"
icon_hientranghethong = "//*[@class='tab-content']//*[@title='Hiện trạng hệ thống']"
hientranghethong_x = "//*[@id='panelStatus']//*[@src='/Images/s_icon_x.png']"
icon_ynghiabieutuongxe = "//*[@src='/Images/s_icon_question.png']"
ynghiabieutuongxe_x = "//*[@id='closeMeaningOfIcon']"
xemlailotrinh = "//*[text()='Xem lại lộ trình ']"
tamgioganday = "//*[text()='8h gần đây']"
xemnhanh = "/html/body/div[17]/div[2]/div[2]/div[1]"
# xemnhanh = "//*[text()='Xem nhanh']"
check_popup_xemnhanhlotrinh = "//*[@id='divViewRouteQuick']"
xemnhanhlotrinh_xoa = "//*[@id='divViewRouteQuick']//*[@title='Xóa lộ trình']"
xemnhanhlotrinh_x = "//*[@id='divViewRouteQuick']//*[@title='Đóng']"
xemchitiettrencuasomoi = "/html/body/div[17]/div[2]/div[2]/div[2]"
# trongngay = "//*[text()='Trong ngày']"
trongngay = "/html/body/div[18]/div[2]/div[2]/div[9]"
tuychon = "/html/body/div[18]/div[2]/div[2]/div[10]"
nhapthongtinxe = "/html/body/div[20]/div[2]/div[2]/div[2]"
# nhapthongtinxe = "//*[text()='Nhập thông tin xe']"
popupthongtinxe_trongtaiinput = "//*[@id='vehicleInfomation']/div[2]/table/tbody/tr[6]/td[2]/input"
popupthongtinxe_capnhat = "//*[@id='ctl00_MainContent_vehicleInfoBGT_BtnUpdate']"
capnhatthanhcong = "//*[text()='Cập nhật thành công']"
ok = "//*[text()='OK']"
huy = "//*[@id='vehicleInfomation']//*[text()='Hủy']"
xemlotrinhnhieuxe = "/html/body/div[20]/div[2]/div[2]/div[3]"
hientrang = "/html/body/div[20]/div[2]/div[2]/div[4]"
check_danhsachxe_hientrang = "//*[@class='leaflet-popup-content-wrapper']"
gannhomdacbiet_hover = "//*[text()='Gán nhóm đặc biệt']"
themnhomdacbiet = "/html/body/div[19]/div[2]/div[2]/div"
check_themnhomdacbiet = "//*[@id='masterTwoColumnRight']/div/div/div/table/tbody/tr[1]/td"
anxe = "/html/body/div[20]/div[2]/div[2]/div[6]"
anxe_antoanbotrang = "//*[@id='panelHideVehicle']/div/div[2]/div[3]/div[2]/div/div[1]/input"
anxe_truyen = "//*[@id='panelHideVehicle']/div/div[2]/div[4]/div[2]/div/div[1]/input"
anxe_nguyennhan = "//*[@id='panelHideVehicle']/div/div[2]/div[5]/div[2]/select"
anxe_nguyennhan_xetainan = "//*[@id='panelHideVehicle']/div/div[2]/div[5]/div[2]/select//*[@value='3']"
anxe_ghichu = "//*[@id='panelHideVehicle']/div/div[2]/div[6]/div[2]/textarea"
luu = "//*[@id='panelHideVehicle']//*[text()='Lưu']"
icon_danhsachxedangan = "//*[@title='Danh sách xe đang ẩn']"
check_danhsachxedangan_tenphuongtien = "//*[@id='panelFavourite']/div/div[8]/table/tbody/tr[1]/td[2]"
icon_danhsachxedangan_x = "//*[@id='panelFavourite']/div/div[8]/table/tbody/tr[1]//*[@src='/Images/delete_item.png']"
thongtinthietbi = "/html/body/div[20]/div[2]/div[2]/div[7]"
check_danhsachxe_thongtinthietbi = "//*[@id='ui-dialog-title-divDeviceInfo']"
thongtinthietbi_x = "//*[@class='ui-icon ui-icon-closethick']"
xemhinhanhnhanh = "/html/body/div[20]/div[2]/div[2]/div[8]"
xemanhcamera = "/html/body/div[20]/div[2]/div[2]/div[9]"
check_xemanhcamera_tuchoitruycap = "//*[text()='Từ chối truy cập']"
xemanhcamera_nd10 = "/html/body/div[20]/div[2]/div[2]/div[10]"
check_xemanhcamera_nd10 = "//*[@id='cameraLeftPanel']/div/table/tbody/tr[1]/td"
giamsatcamera_nd10 = "/html/body/div[20]/div[2]/div[2]/div[11]"
check_giamsatcamera_nd10 = "//*[text()='Giám sát video']"
bieudonhienlieu = "/html/body/div[20]/div[2]/div[2]/div[12]"
check_popupbieudonhienlieu = "//*[@id='popUpBox']/div/div/div[2]"
bieudonhienlieu_x = "//*[@id='popUpBox']//*[@title='Đóng']"
bieudonhienlieumoi = "/html/body/div[20]/div[2]/div[2]/div[13]"
check_popupbieudonhienlieumoi = "//*[@class='popUpBox popup-online ui-draggable']/div/div/div[1]"
bieudonhienlieumoi_x = "//*[@class='popUpBox popup-online ui-draggable']//*[@title='Đóng']"
bieudonhietdo = "/html/body/div[20]/div[2]/div[2]/div[14]"
check_popupbieudonhietdo = "//*[text()='Xe chưa cấu hình hiển thị nhiệt độ.']"
khoangcachdencacxe = "/html/body/div[20]/div[2]/div[2]/div[15]"
khoancach_ngan = "//*[@class='float-left;']/table/tbody/tr[1]/td[1]"
khoancach_dai = "//*[@class='float-left;']/table/tbody/tr[1]/td[2]/div[3]"
button_keo = "//*[@class='float-left;']/table/tbody/tr[1]/td[2]/div[1]/div/a"
khoancachdencacxe_x = "//*[@id='panelMeasureDistance']/div/div[1]//*[@src='/Images/s_icon_x.png']"
khoangcachdencacdiem = "/html/body/div[20]/div[2]/div[2]/div[16]"
goicuoccamera = "//*[@pid='panelTabBacam1']"
popupthongtinxe_masorieng = "//*[@id='panelTabNormal1']/div[1]/div[1]"
popupthongtinxe_bienso = "//*[@id='panelTabNormal1']/div[1]/div[2]"
popupthongtinxe_giocapnhat = "//*[@id='panelTabNormal1']/div[1]/div[5]"
popupthongtinxe_vantocgps = "//*[@id='panelTabNormal1']/div[1]/div[8]"
popupthongtinxe_vantocco = "//*[@id='panelTabNormal1']/div[1]/div[11]"
popupthongtinxe_dungdo = "//*[@id='panelTabNormal1']/div[1]/div[14]"
popupthongtinxe_dangdo = "//*[@id='panelTabNormal1']/div[1]/div[16]"
popupthongtinxe_kmtrongngay = "//*[@id='panelTabNormal1']/div[1]/div[17]"
popupthongtinxe_may = "//*[@id='panelTabNormal1']/div[1]/div[20]"
popupthongtinxe_dieuhoa = "//*[@id='panelTabNormal1']/div[1]/div[23]"
popupthongtinxe_diachi = "//*[@id='panelTabNormal1']/div[1]/div[26]"
popupthongtinxe_nhienlieu = "//*[@id='panelTabNormal1']/div[1]/div[29]/div[2]"
popupthongtinxe_laixe = "//*[@id='panelTabNormal1']/div[2]/div[2]"
popupthongtinxe_dienthoai = "//*[@id='panelTabNormal1']/div[2]/div[4]"
popupthongtinxe_dienthoai1 = "//*[@id='panelTabNormal1']/div[2]/div[5]"
popupthongtinxe_giaypheplaixe = "//*[@id='panelTabNormal1']/div[2]/div[8]"
popupthongtinxe_quatocdo = "//*[@id='panelTabNormal1']/div[2]/div[11]"
popupthongtinxe_thoigianlaixelientuc = "//*[@id='panelTabNormal1']/div[2]/div[14]"
popupthongtinxe_thoigianlaixetrongngay = "//*[@id='panelTabNormal1']/div[2]/div[17]"
popupthongtinxe_thongtinthenho = "//*[@id='panelTabNormal1']/div[2]/div[20]"
popupthongtinxe_soquanly = "//*[@id='panelTabNormal1']/div[2]/div[23]"
popupthongtinxe_thongtinphi = "//*[@id='panelTabNormal1']/div[3]/div[2]"
popupthongtinxe_goicuocdichvuvienthong = "//*[@id='panelTabBacam1']/div[1]/div[5]"
popupthongtinxe_nhamang = "//*[@id='panelTabBacam1']/div[1]/div[8]"
popupthongtinxe_dungluonggoicuoc = "//*[@id='panelTabBacam1']/div[1]/div[11]"
popupthongtinxe_songayluutru = "//*[@id='panelTabBacam1']/div[1]/div[14]"
popupthongtinxe_sokenhluutru = "//*[@id='panelTabBacam1']/div[1]/div[17]"
popupthongtinxe_tinhnangdinhvi = "//*[@id='panelTabBacam1']/div[1]/div[20]"
popupthongtinxe_tinhnanganh = "//*[@id='panelTabBacam1']/div[1]/div[23]"
popupthongtinxe_tinhnangvideo = "//*[@id='panelTabBacam1']/div[1]/div[26]"
popupthongtinxe_kenhlapcamera = "//*[@id='panelTabBacam1']/div[1]/div[32]"
popupthongtinxe_kenhhoatdong = "//*[@id='panelTabBacam1']/div[1]/div[35]"
popupthongtinxe_dungluongocung = "//*[@id='panelTabBacam1']/div[1]/div[38]"
popupthongtinxe_mangketnoi = "//*[@id='panelTabBacam1']/div[1]/div[41]"
icon_hientranghethong1 = "//*[@class='toolboxRightButton']//*[@src='/Images/btn_rightPanel_hienTrang.png']"
hientranghethong_biensoinput = "//*[@id='panelStatus']/div/div[4]/table/tbody/tr/td[4]/input"
timkiem_icon2 = "//*[@class='SearchSelect']/span"
danhsachxe2g_x = "//*[@id='divListVehicle2G']//*[@src='/Images/s_icon_x.png']"
chuotphaimap_phongto = "/html/body/div[21]/div[2]/div[2]/div[1]"
chuotphaimap_thunho = "/html/body/div[21]/div[2]/div[2]/div[2]"
canhbaoquatocdo_x = "//*[@id='warningSpeedOverTimeLine']//*[@src='/icons/IconX.png']"
chuotphaimap_trungtamoday = "/html/body/div[21]/div[2]/div[2]/div[3]"
giamsat_iconphongto = "//*[@title='Zoom in']"
giamsat_iconthunho = "//*[@title='Zoom out']"
check_trungtamoday = "//*[text()='Bộ công an test']"
chuotphaimap_xemdiachi = "/html/body/div[21]/div[2]/div[2]/div[4]"
check_xemdiachi = "//*[@class='bootbox-body']"
chuotphaimap_dokhoangcach = "/html/body/div[21]/div[2]/div[2]/div[5]"
check_dokhoangcach_thongbao = "//*[@id='tdDistance']"
chuotphaimap_chihuong = "/html/body/div[21]/div[2]/div[2]/div[6]"
canhbao_x = "//*[@id='panelWarningOnline']//*[@src='/Images/s_icon_x.png']"
chihuong_diema = "//*[@src='/icons/DanDuong/diemdi.png']"
chihuong_diemb = "//*[@src='/icons/DanDuong/diemden.png']"
chihuong_googlemap = "//*[@id='btnGoGoogle']"
chihuong_chihuong = "//*[@id='btnGo']"
chihuong_icondaovitri = "//*[@src='/icons/DanDuong/refresh.png']"
chihuong_thoat = "//*[@id='btnExit']"
chuotphaimap_chidanduong = "/html/body/div[21]/div[2]/div[2]/div[7]"
chidanduong_diemdi = "//*[@id='ds_ds_new']/div[3]/table/tbody/tr[2]/td/div"
# chidanduong_diemden = "//*[@id='ds_ds_new']/div[3]/table/tbody/tr[4]/td/div"
chidanduong_diemden = "//*[@id='findroad_txtEnd']"
chidanduong_timchiduong = "//*[@id='findroad_btnSearch']"
chidanduong_loaixe = "//*[@id='findroad_bot_vehicletype']"
chidanduong_chiphicauduong = "//*[@id='findroad_detailscharge']/td"
chidanduong_chiphinhienlieu = "//*[@id='findroad_detailsfuel_hideshow']"
chidanduong_cacchiphikhac = "//*[@id='findroad_detailsother_hideshow']"
chidanduong_cacchiphikhac_chonloaiphi = "//*[@id='findroad_others_input']/td[2]/div/button"
chidanduong_diemdi_iconchon = "//*[@class='StartSearchBox SearchBox']/a/span"
chidanduong_diemdi_timxe = "//*[@id='StartliVehicle']"
chidanduong_diemdiinput = "//*[@id='findroad_txtStart']"
chidanduong_diemden_iconchon = "//*[@class='EndSearchSelect SearchSelect Address LatLng']/span"
chidanduong_diemden_timxe = "//*[@id='EndliVehicle']"
chidanduong_diemdeninput = "//*[@id='findroad_txtEnd']"
check_chidanduong_quangduong = "//*[@id='findroad_totaldistance']"
check_chidanduong_timtheodiem = "//*[@id='findroad_totalcost']"
check_chidanduong_giatien = "//*[@id='findroad_totalcost']"
chidanduong_diemdi_tendiem = "//*[@id='StartliLandmarkName']"
xe1 = "//*[@id='tblVehicleList']/tbody/tr[1]/td[2]"
xe2 = "//*[@id='tblVehicleList']/tbody/tr[2]/td[2]"
chidanduong_diemdi_tendiem1 = "//*[@id='StartliLandmarkName']"
chidanduong_diemdi_tendiem1input = "//*[@id='findroad_txtStart']"
chidanduong_diemden_tendiem1 = "//*[@id='StartliLandmarkName']"
chidanduong_diemden_tendiem1input = "//*[@id='findroad_txtEnd']"
chidanduong_diemden_iconchon2 = "//*[@class='EndSearchSelect SearchSelect LatLng']/span"
chidanduong_diemden_tendiem2 = "//*[@id='EndliLandmarkName']"
check_chidanduong_nhienlieu = "//*[@id='ds_ds_new']/div[3]/table/tbody/tr[12]/td/div[1]/table/tbody/tr[3]/td[3]"
timtheolotrinh = "//*[text()='Tìm theo lộ trình']"
chidanduong_nhomphuongtien = "//*[@id='findroad_ddlVehicleGroup']"
chidanduong_nhomphuongtien1 = "//*[@id='findroad_ddlVehicleGroup']/option[2]"
chidanduong_phuongtieninput = "//*[@placeholder='Chọn phương tiện']"
timtheolotrinh_giobatdau = "//*[@id='findroad_fromTimePicker']"
timtheolotrinh_gioketthuc = "//*[@id='findroad_toDatePicker']"
chuotphaimap_taodiembando = "/html/body/div[21]/div[2]/div[2]/div[9]"
taodiem_tendiem = "//*[@id='txtName']"
taodiem_laydiachibando = "//*[@id='chkAddressMap']"
taodiem_nhaptoado = "//*[@id='chkInputCoords']"
taodiem_kinhdo = "//*[@id='txtLongitude']"
taodiem_vido = "//*[@id='txtLatitude']"
taodiem_loaidiem = "//*[@id='ddlLandmarkType']"
taodiem_tenrieng = "//*[@id='txtPrivatename']"
taodiem_mota = "//*[@class='quantri-box popUpBox']//*[@id='txtDescription']"
taodiem_sophutdungdo = "//*[@id='txtNumberMinuteStop']"
taodiem_diemkiemsoat = "//*[@id='chkLandmarkManagement']"
taodiem_hienthidiem = "//*[@id='chkLandmarkVisible']"
taodiem_bankinh = "//*[@id='txtRadius']"
taodiem_huy = "//*[@id='btCancel']"
taodiem_luu = "//*[@id='btnSaveLandmark']"
check_message_taodiem = "//*[@class='bootbox modal fade bootbox-alert in']/div/div/div[1]"
check_message_taodiem1 = "//*[text()='Cập nhật thành công']"
taodiem_chon = "//*[@src='https://gps.binhanh.vn/icons/point/baido.png']"
taodiem_capnhat= "//*[@id='btnUpdateLandmark']"
taodiem_xoa = "//*[@id='btnDelete']"
check_message_xoadiem = "//*[text()='Xóa thành công']"
chuotphaimap_taovunglotrinh = "/html/body/div[21]/div[2]/div[2]/div[10]"
checkpopup_taovunglotrinh = "//*[@id='frmCreateSurround']//*[@class='float_left Header']"
taovunglotrinh_iconx = "//*[@id='frmCreateSurround']//*[@src='/Images/s_icon_x.png']"
chuotphaimap_timxetrongvung = "/html/body/div[21]/div[2]/div[2]/div[11]"
giamsat_diem2 = "//*[@src='https://gps.binhanh.vn/icons/point/19.png']"
check_timxetrongvung = "//*[@id='panelSearch']/div/div[2]/div/b"
chuotphaimap_timxegannhat = "/html/body/div[21]/div[2]/div[2]/div[12]"
checkpopup_timxegannhat = "//*[@id='panelSearchNearest']/div/div[2]/div/b"
chuotphaimap_cauhinhhienthinhomdiem = "/html/body/div[21]/div[2]/div[2]/div[14]"
cauhinhhienthinhomdiem_chuachonnhom = "//*[@id='divConfigGroupLandmark']/div[4]/input[1]"
cauhinhhienthinhomdiem_tramthuphi = "//*[@id='divConfigGroupLandmark']/div[4]/input[2]"
cauhinhhienthinhomdiem_hienthivungbao = "//*[@id='divConfigGroupLandmark']/div[5]/table/tbody/tr[3]/td/input"
cauhinhhienthinhomdiem_hienthitendiem = "//*[@id='divConfigGroupLandmark']/div[5]/table/tbody/tr[4]/td/input"
chuotphaimap_luuthongtinhienthi = "//*[@id='btnSaveConfigGroupLandmark']"
check_tramthuphi_vungbao = "/html/body/div[3]/form/div[3]/div[3]/div[8]/div[2]/div[3]//*[@fill-opacity='0.2']"
check_tramthuphi_tendiem = "//*[text()='Trạm thu phí Cao tốc Pháp Vân - Cầu Giẽ (Liên Ninh)']"
chuotphaimap_luuthongtinhienthi_ok = "//*[@data-bb-handler='ok']"
check_message_luucauhinhhienthi = "//*[@class='bootbox modal fade bootbox-alert in']/div/div/div[1]/div"
check_chuachonnhom_vungbao = "/html/body/div[3]/form/div[3]/div[3]/div[8]/div[2]/div[3]//*[@fill-opacity='0.5']"
check_chuachonnhom_tendiem = "//*[@class='leaflet-marker-icon custom-marker-leaflet leaflet-zoom-animated leaflet-interactive']//*[text()='Nhà của Trường1']"
chuotphaimap_cauhinhkhoidong = "/html/body/div[21]/div[2]/div[2]/div[15]"
check_popupcauhinhhienthibando = "//*[@id='frmConfigMap']//*[@class='float_left Header']"
cauhinhienthi_loaibando = "//*[@id='ddlMapType']"
cauhinhienthi_loaibando_vetinhbinhanh = "//*[@id='ddlMapType']//*[@value='5']"
cauhinhienthi_kinhdo = "//*[@id='txtLongitude']"
cauhinhienthi_vido = "//*[@id='txtLatitude']"
cauhinhienthi_muczoombando = "//*[@id='txtMapZoom']"
cauhinhienthi_luu = "//*[@id='btnSaveMapConfig']"
cauhinhienthi_huy = "//*[@id='btnCancelFormMapConfig']"
cauhinhienthi_loaibando_bando = "//*[@id='ddlMapType']//*[@value='2']"
chuotphaimap_bieudonhienlieumoi = "/html/body/div[21]/div[2]/div[2]/div[16]"
check_popup_bieudonhienlieumoi = "//*[@class='bootbox modal fade bootbox-alert in']/div/div/div[1]/div"
chuotphaimap_gstheotuyenmau = "/html/body/div[21]/div[2]/div[2]/div[17]"
check_popup_gstheotuyenmau = "//*[@id='popUpBoxVehicleTrackingForm']/div/div[1]/div[2]"
chuotphaimap_gstheotuyenmau_iconx = "//*[@id='btnCloseVTWRForm']"
danhsachcongty = "//*[text()='Danh sách công ty']"
danhsachcongty_loai = "//*[@name='ctl00$ctl00$MainContent$Content$companySearch$ddlSearchType']"
danhsachcongty_loai_tencongty = "//*[@name='ctl00$ctl00$MainContent$Content$companySearch$ddlSearchType']//*[@value='2']"
danhsachcongty_noidung = "//*[@placeholder='Nội dung']"
danhsachcongty_timkiem = "//*[@id='btnSearch']"
check_timkiem_congty = "//*[@id='ctl00_ctl00_MainContent_Content_grvReport']/tbody/tr[2]/td[2]"
danhsachcongty_icondencongty = "//*[@src='../../Images/s_icon_GotoCompany.png']"
giamsat = "//*[@id='ModuleOnline']"
danhsachxe_dungtat = "//*[text()='Dừng - Tắt']"
chuotphaimap_dieuxedituyen = "/html/body/div[21]/div[2]/div[2]/div[19]"
check_popup_dieuxedituyen = "//*[@id='divVehicleOperator']/div[1]/div/div"
dieuxedituyen_tuyendichuyen = "//*[@id='txtRoute']"
dieuxedituyen_diemnhanhang = "//*[@id='txtRecive']"
dieuxedituyen_bienkiemsoat = "//*[@id='txtVehiclePlateOpertator']"
dieuxedituyen_ghichu = "//*[@id='txtNote']"
dieuxedituyen_sdtlaixe = "//*[@id='txtPhone']"
dieuxedituyen_laixe = "//*[@id='txtDriver']"
dieuxedituyen_luuvatieptuc = "//*[@id='btnaddVhOperatorCon']"
dieuxedituyen_themmoi = "//*[@id='btnaddVhOperator']"
dieuxedituyen_thoat = "//*[@id='btnCloseVhOperator']"
check_gs_timkiem_timxe = "//*[@class='leaflet-popup-content-wrapper']/div/div[3]/div[1]/div[2]"
timkiem_timxe_input1 = "//*[@id='toolbox']//*[@placeholder='Nhập xe cần tìm']"
check_gs_mauxe = "//*[@id='idClearOnline']/table/tbody/tr[1]"
check_gs_tendiem = "//*[@class='leaflet-popup-content-wrapper']/div/div/div[2]"
check_gs_timtoado_kinhdo = "//*[@class='leaflet-popup-content-wrapper']/div/div/div[5]"
check_gs_timtoado_vido = "//*[@class='leaflet-popup-content-wrapper']/div/div/div[8]"
vinconshipdanang1 = "//*[text()='VICONSHIPDANANG1 [950]']"
tongsoxe_duoi = "//*[@id='display_allsumvehicle']"
ungroup = "//*[text()='Không nhóm đội [1010]']"
ungroup_1 = "//*[text()='ungroup_1 [1010]']"
e43E02743 = "//*[text()='43E02743 [950]']"
trangthai_tatca = "//*[@id='ddlVehicleState']//*[@selected='selected']"
check_popup_hientranghethong = "//*[@id='panelStatus']/div/div[2]/b"
check_popup_ynghiabieutuongxe = "//*[@id='popUpBox_theMeaningOfIcon']//*[@class='float_left Header']"
nhapthongtinxe_x = "//*[@id='vehicleInfomation']//*[@id='imgClosevehicleInfo']"
popupthongtinxe_loaihinhvantai_vantaihanghoa = "//*[@id='vehicleInfomation']//*[@value='500']"
popupthongtinxe_vantaidangkychaynoithanh = "//*[@id='ctl00_MainContent_vehicleInfoBGT_ckCustomerInBGT']"
check_popupthongtinxe_loaihinhvantai = ""
popupthongtinxe_chopheptichtruyendulieu = "//*[@id='ctl00_MainContent_vehicleInfoBGT_ckBGTForward']"
check_popupthongtinxe_congty = "//*[@id='ctl00_MainContent_vehicleInfoBGT_ddlBranch_ddlBranch']/option[1]"
check_popupthongtinxe_trongtai = "//*[@id='ctl00_MainContent_vehicleInfoBGT_txtWeightBGT']"
popupthongtinxe_loaihinhvantai_xekhachtuyencodinh = "//*[@id='vehicleInfomation']//*[@value='100']"
danhsachxe_xe1 = "//*[@id='idClearOnline']/table/tbody/tr[1]"
popupthongtinxe_capnhat1 = "//*[@id='ctl00_MainContent_vehicleInfoBGT_BtnUpdate']"
check_giamsatnhieuxe_xe1 = "//*[@id='boxRight']/div[1]"
check_giamsatnhieuxe_xe3 = "//*[@id='boxRight']/div[3]"
hover_giamsat = "//*[@id='boxRight']/div[1]/div[6]"
hover_giamsat_phongto = "//*[@id='boxRight']/div[1]/div[6]/ul/li[2]"
check_giamsat_iconphongto = "//*[@class='c leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom']"
hover_giamsat_phongto_x = "//*[@class='dZoom']//*[@src='/icons/onlines/close.png']"
giamsatnhieuxe_iconx3 = "//*[@id='boxRight']/div[3]/div[5]"
giamsatnhieuxe_iconx2 = "//*[@id='boxRight']/div[2]/div[5]"
giamsatnhieuxe_iconx1 = "//*[@id='boxRight']/div[1]/div[5]"
check_danhsachxe_thongtinxe = "//*[@pid='panelTabNormal1']"
check_danhsachxe_hientrang_x = "//*[@class='leaflet-popup-close-button']"
hientrang_goicuoc = "//*[@pid='panelTabBacam1']"
check_popup_anxe = "//*[@id='panelHideVehicle']//*[@class='header-title']"
giamsat_anxe_dong = "//*[@id='panelHideVehicle']//*[text()='Đóng']"
danhsachxe_tenphuongtien1 = "//*[@id='idClearOnline']/table/tbody/tr[1]/td[2]/div[2]"
check_danhsachxedangan_trangthai = "//*[@id='panelFavourite']/div/div[8]/table/tbody/tr[1]/td[3]"
check_danhsachxedangan_truyentcdb = "//*[@id='panelFavourite']/div/div[8]/table/tbody/tr[1]/td[4]//*[@src='/Images/tick.gif']"
icon_danhsachxedangan_nguyennhan = "//*[@id='ddlErrorType']//*[@value='3']"
icon_danhsachxedangan_timkiem = "//*[@id='imgSearchVehicleInterest']"
check_capnhatxe_ghichu = "//*[@id='txtNoteErrorDetail']"
capnhatxe_antrengiamsat = "//*[@id='radHideTracking']"
luuvadungtruyen = "//*[@id='btnErrorSaveAndStopTransfer']"
icon_danhsachxedangan_x_tichtruyen = "//*[@class='btn btn-primary btn-transfer']"
check_xemhinhanhnhanh = "//*[@class='pp_content_container']"
xemhinhanhnhanh_dong = "//*[@class='pp_overlay']"
goto_vinconshipdanang = "//*[text()='Viconship Đà Nẵng [950]']"
check_xemanhcamera = "//*[@class='tableBoxHeader']"
check_popup_khoangcachdencacxe = "//*[@id='panelMeasureDistance']/div/div[2]/table/tbody/tr[1]/td[1]"
check_khoangcach = "//*[@class='float-left;']/table/tbody/tr[1]/td[2]/div[2]"
khoangcachdencacxe_tenxe1 = "//*[@class='searchMeasureContent']/tr[1]/td[2]/div"
khoangcachdencacxe_teninput = "//*[@id='filter_name']"
bieudoluuluong = "/html/body/div[20]/div[2]/div[2]/div[14]"
check_popup_bieudoluuluong = "//*[@id='popUpBoxFlow']//*[@class='float_left Header']"
bieudoluuluong_iconx = "//*[@id='popUpBoxFlow']//*[@id='btnCloseFlowChart']"
gstheotuyenmau = "/html/body/div[20]/div[2]/div[2]/div[18]"
gstheotuyenmau_iconx = "//*[@id='btnCloseVTWRForm']"
goto_nhapmaxninput = "//*[@placeholder='Nhập mã XN']"
goto_dencongty = "//*[@class='blog-info']//*[text()='Đến công ty']"
taonhanhdonhang = "/html/body/div[20]/div[2]/div[2]/div[19]"
check_popuptaonhanhdonhang = "//*[@class='modal_content popUpBox']/table[1]/tbody/tr[1]/td/div"
taonhanhdonhang_dong = "//*[@class='btn btn-primary btnCloseAddOrder']"
goto_1010congtykhongconhomdoi = "//*[text()='1010_Công ty không có nhóm đội [1010]']"
nhaplichchuyenxe = "/html/body/div[20]/div[2]/div[2]/div[20]"
check_popup_themmoichuyen = "//*[@id='divTripAdd']/div[1]/div/div/span"
nhaplichchuyenxe_dong = "//*[@id='divTripAdd']/div[3]/div/div/input[1]"
iconphuongtienthieuthongtintichtruyen = "//*[@title='Phương tiện thiếu thông tin tích truyền']"
icontheodoichuyenhang = "//*[@title='Theo dõi chuyến hàng']"
icontheodoichuyenhang_ok = "//*[@class='bootbox modal fade bootbox-alert in']//*[@class='btn btn-primary']"
check_popuptheodoichuyenhang = "//*[@id='panelCpm']/div/div[2]/b"
icontheodoichuyenhang_x = "//*[@id='panelCpm']//*[@title='Đóng']"
iconxemanhcamera = "//*[@title='Xem ảnh Camera']"
check_popuphientranghethong = "//*[@id='panelStatus']/div/div[2]/b"
check_popupdanhsachxedangan = "//*[@id='panelFavourite']/div/div[2]"
danhsachxedangan_x = "//*[@id='panelFavourite']//*[@title='Đóng']"
check_popupdanhsachxe2g = "//*[@id='divListVehicle2G']/div[1]"
icon_danhsachxe2g = "//*[@title='Danh sách xe 2G']"
icon_canhbaotimeline = "//*[@title='Cảnh báo Timeline']"
check_popupcanhbaotimeline = "//*[@id='warningTimeline']/table/tbody/tr[1]/td[1]/div"
canhbaotimeline_x = "//*[@id='closeTimeline']"
iconthongtinxetoihandivaophocam = "//*[@title='Thông tin xe tới hạn đi vào phố cấm']"
iconcanhbaoxechuatoidiem = "//*[@title='Cảnh báo xe chưa tới điểm']"
# check_popupcanhbaoxechuatoidiem = "//*[@id='PanelDestinationAlertOnline']/div/div[2]/div[1]"
check_popupcanhbaoxechuatoidiem = "//*[@id='PanelDestinationAlertOnline']/div/div[3]/table/thead/tr[1]/th[1]"
canhbaoxechuatoidiem_x = "//*[@id='PanelDestinationAlertOnline']//*[@class='closeRightPanel']"
iconcanhbao = "//*[@title='Cảnh báo']"
check_popupcanhbao = "//*[@id='panelWarningOnline']/div/div[2]/div[1]"
popupthongtinxe_nomay = "//*[@id='panelTabNormal1']/div[1]/div[16]"
check_dokhoangcach = "//*[@id='divDistance']//*[@class='float_left Header']"
dokhoangcach_iconxoa = "//*[@id='imgDelete']"
dokhoangcach_iconx = "//*[@id='imgDistance']"
check_popup_dokhoangcach = "//*[text()='0.03 km']"
check_popupchihuong = "//*[@id='ds_ds']"
check_chihuong_diema = "//*[@class='undefined']//*[@src='/icons/DanDuong/diemdi.png']"
check_chihuong_diemb = "//*[@class='undefined']//*[@src='/icons/DanDuong/diemden.png']"
check_chihuong_google = "//*[@src='//maps.gstatic.com/consumer/images/icons/1x/ic_directions_filled_blue900_24px.png']"
chihuong_icondoivitri2diem = "//*[@src='/icons/DanDuong/refresh.png']"
popupthongtinxe_dungxenomay = "//*[@id='panelTabNormal1']/div[1]/div[16]"
check_popupchidanduong = "//*[@id='findroad_landmark_tab']"
chidanduong_iconx = "//*[@id='findroad_btnExit']"
check_chidanduong_diemdi = "//*[@class='undefined']//*[@src='/icons/DanDuong/diemdi.png']"
check_chidanduong_diemden = "//*[@class='undefined']//*[@src='/icons/DanDuong/diemden.png']"
chidanduong_icondoivitri = "//*[@id='findroad_revert_btn']"
check_popuptimtheolotrinh = "//*[text()='Tìm theo lộ trình']"
danhsachxe_dichuyen = "//*[@id='td_movesumvehicle']"
timtheolotrinh_ngaybatdau = "//*[@id='findroad_fromDatePicker']"
check_timtheolotrinh_quangduong = "//*[@id='findroad_totaldistance']"
check_timtheolotrinh_changthuphi = "//*[@id='ds_ds_new']/div[3]/table/tbody/tr[12]/td/div[1]/table/tbody/tr[3]/td[2]"
check_timtheolotrinh_nhienlieudinhmuc = "//*[@id='ds_ds_new']/div[3]/table/tbody/tr[12]/td/div[1]/table/tbody/tr[3]/td[3]"
check_timtheolotrinh_chiphidukien = "//*[@id='findroad_totalcost']"
check_timtheolotrinh_tomtatlotrinh = "//*[@id='findroad_detailsroute_summary']"
check_popuptaodiem = "//*[@class='float_left Header addlandmarkHeader']"
taovunglotrinh_huy = "//*[@id='btCancel']"
close = "//*[@class='leaflet-popup-close-button']"
timxetrongvung_capnhatmoidulieu = "//*[@id='searchVehicleRefresh']"
timxetrongvung_ketxuat = "//*[@id='btnExportExcelSearch']"
timxetrongvung_iconx = "//*[@id='imageClose']"
giamsat_diem1 = "//*[@src='https://gps.binhanh.vn/icons/point/concrete_station.png']"
giamsat_diem3 = "//*[@src='https://gps.binhanh.vn/icons/point/recycle_bin_3.png']"
timxegannhat_iconx = "//*[@id='panelSearchNearest']//*[@title='Đóng']"
check_popupcauhinhhienthinhomdiem = "//*[@class='quantri-box popUpBox']//*[@class='float_left Header']"
chuotphaimap_cauhinhhienthinhomdiem_iconx = "//*[@class='quantri-box popUpBox']//*[@src='/Images/s_icon_x.png']"
chuotphaimap_cauhinhhienthinhomdiem_iconx1 = "//*[@id='frmConfigGroupLandmark']//*[@src='/Images/s_icon_x.png']"
check_messagetattatca = "//*[@class='bootbox-body']"
chuotphaimap_bieudonhienlieu = "/html/body/div[21]/div[2]/div[2]/div[16]"
dieuxedicheck_popupdieuxedituyentuyen_thoat = "//*[@id='divVehicleOperator']/div[1]/div/div"
vehicle = "//*[@id='ModuleRoute']"
check_popup_route = "//*[@id='signinPanel']//*[@class='active']/a"
license_plates = "//*[@placeholder='Biển số']"
km_move = "//*[@id='TongKM']"
route_icondownloaddata = "//*[@id='btnGetData']"
check_iconprintroute = "//*[@id='btnPrint']"
check_printroute_licenseplate = "//*[@id='lblInfo']"
icon_downloadexcel = "//*[@id='btnExportExcel']"
khongcocamera = "//*[text()='Phương tiện không sử dụng camera video giám sát.']"
check_popuproute_loaddata = "//*[@id='list']/div[2]"
icon_runroute = "//*[@id='ViewRoute']"
check_timeroute = "//*[@id='idthoigian0']"
icon_dataconfig = "//*[@id='columnOption']"
checkpopup_dataconfig = "//*[@id='trVgps']/td[2]"
dataconfig_vgps = "//*[@id='chkVgps']"
dataconfig_vco = "//*[@id='chkCo']"
dataconfig_vbgt = "//*[@id='chkVbgt']"
dataconfig_km = "//*[@id='chkKm']"
dataconfig_displayfuel = "//*[@id='chkFuel']"
dataconfig_doorstatus = "//*[@id='chkCua']"
dataconfig_harmonicstatus = "//*[@id='chkDieuHoa']"
dataconfig_machinestatus = "//*[@id='chkMay']"
dataconfig_longitude_latitude = "//*[@id='chkLngLat']"
dataconfig_displayadress = "//*[@id='chkAddress']"
check_namecolumn_vgps = "//*[@id='idvantocgps']"
check_namecolumn_vco = "//*[@id='idvantocco']"
check_namecolumn_vbgt = "//*[@id='idvattocbgt']"
check_namecolumn_fuel = "//*[@id='idfuel']"
check_namecolumn_km = "//*[@id='idkm']"
check_namecolumn_door = "//*[@id='idcua']"
check_namecolumn_harmonic = "//*[@id='iddieuhoa']"
check_namecolumn_machine = "//*[@id='idmay']"
check_namecolumn_longitude_latitude = "//*[@id='idLngLat']"
check_namecolumn_adress = "//*[@id='idAddr']"
check_totalkm = "//*[@id='TongKM']"
icon_route_display_config = "//*[@title='Cấu hình hiển thị lộ trình']"
checkpopup_routedisplayconfig = "//*[@id='divListConfigViewRoute']//*[@class='float_left Header']"
icon_route_display_config_cancel = "//*[@id='divListConfigViewRoute']//*[@id='btCancel']"
route_liscense_plate = "//*[@id='divListConfigViewRoute']//*[@id='txtVehiclePlate']"
combined_parking = "//*[@id='chkGroupRecord']"
note_lost_signal = "//*[@id='chkStateSignalLoss']"
stoptime = "//*[@id='lblTimeStopOff']"
lost_signal_time = "//*[@id='trTimeSignalLoss']/td[1]/label"
defaultconfig = "//*[@id='divListConfigViewRoute']//*[@id='Button1']"
routedisplayconfig_save = "//*[@id='divListConfigViewRoute']//*[@id='btnSave']"
managerment = "//*[@id='ModuleAdmin']"
type_vehicle = "//*[@id='column-right']//*[@id='VEHICLETYPEMANAGER']"
name_typevehicle1 = "//*[@class='table table-bordered']/tbody/tr[2]/td[2]/span"
typevehicle_search = "//*[@placeholder='Nhập loại phương tiện để tra cứu']"
typevehicle_buttonsearch = "//*[@class='btn btn-primary cssBtnSearch']"
check_page_type_vehicle = "//*[@class='tableBoxHeader']"
managerment_typevehicle = "//*[@id='column-right']//*[@id='VEHICLETYPEMANAGER']"
typevehicle_addnew = "//*[@id='column-right']//*[@class='btn btn-primary btnAdd']"
typevehicle = "//*[@id='txtVhType']"
number_of_seats = "//*[@id='txtWeightSeat']"
km_maintenance = "//*[@id='txtQuotaKm']"
addnew_license_plates = "//*[@id='txtVehicles']"
addnew_infovehicle_buttonsave = "//*[@id='divInsertUpdate']//*[@value='Lưu']"
save_successfully = "//*[text()='Thêm mới thành công']"
check_typevehicle = "//*[@class='table table-bordered']/tbody/tr[6]/td[2]/span"
check_typevehicle_icondelete = "//*[@class='table table-bordered']/tbody/tr[6]/td[7]"



